// ============================================================================
// BASIRA — Surah metadata (114 surahs): [num, arabic, transliteration, english, ayahs, place]
// Place: "Makkah" | "Madinah"
// ============================================================================

export interface SurahMeta {
  number: number;
  arabic: string;
  transliteration: string;
  english: string;
  ayahs: number;
  place: 'Makkah' | 'Madinah';
}

const RAW: [number, string, string, string, number, 'Makkah' | 'Madinah'][] = [
  [1, 'الفاتحة', 'Al-Fatihah', 'The Opening', 7, 'Makkah'],
  [2, 'البقرة', "Al-Baqarah", 'The Cow', 286, 'Madinah'],
  [3, 'آل عمران', "Ali 'Imran", 'Family of Imran', 200, 'Madinah'],
  [4, 'النساء', 'An-Nisa', 'The Women', 176, 'Madinah'],
  [5, 'المائدة', "Al-Ma'idah", 'The Table Spread', 120, 'Madinah'],
  [6, 'الأنعام', "Al-An'am", 'The Cattle', 165, 'Makkah'],
  [7, 'الأعراف', "Al-A'raf", 'The Heights', 206, 'Makkah'],
  [8, 'الأنفال', 'Al-Anfal', 'The Spoils of War', 75, 'Madinah'],
  [9, 'التوبة', 'At-Tawbah', 'The Repentance', 129, 'Madinah'],
  [10, 'يونس', 'Yunus', 'Jonah', 109, 'Makkah'],
  [11, 'هود', 'Hud', 'Hud', 123, 'Makkah'],
  [12, 'يوسف', 'Yusuf', 'Joseph', 111, 'Makkah'],
  [13, 'الرعد', "Ar-Ra'd", 'The Thunder', 43, 'Madinah'],
  [14, 'إبراهيم', 'Ibrahim', 'Abraham', 52, 'Makkah'],
  [15, 'الحجر', 'Al-Hijr', 'The Rocky Tract', 99, 'Makkah'],
  [16, 'النحل', 'An-Nahl', 'The Bee', 128, 'Makkah'],
  [17, 'الإسراء', 'Al-Isra', 'The Night Journey', 111, 'Makkah'],
  [18, 'الكهف', 'Al-Kahf', 'The Cave', 110, 'Makkah'],
  [19, 'مريم', 'Maryam', 'Mary', 98, 'Makkah'],
  [20, 'طه', 'Taha', 'Ta-Ha', 135, 'Makkah'],
  [21, 'الأنبياء', 'Al-Anbiya', 'The Prophets', 112, 'Makkah'],
  [22, 'الحج', 'Al-Hajj', 'The Pilgrimage', 78, 'Madinah'],
  [23, 'المؤمنون', "Al-Mu'minun", 'The Believers', 118, 'Makkah'],
  [24, 'النور', 'An-Nur', 'The Light', 64, 'Madinah'],
  [25, 'الفرقان', 'Al-Furqan', 'The Criterion', 77, 'Makkah'],
  [26, 'الشعراء', "Ash-Shu'ara", 'The Poets', 227, 'Makkah'],
  [27, 'النمل', 'An-Naml', 'The Ant', 93, 'Makkah'],
  [28, 'القصص', 'Al-Qasas', 'The Stories', 88, 'Makkah'],
  [29, 'العنكبوت', "Al-'Ankabut", 'The Spider', 69, 'Makkah'],
  [30, 'الروم', 'Ar-Rum', 'The Romans', 60, 'Makkah'],
  [31, 'لقمان', 'Luqman', 'Luqman', 34, 'Makkah'],
  [32, 'السجدة', 'As-Sajdah', 'The Prostration', 30, 'Makkah'],
  [33, 'الأحزاب', 'Al-Ahzab', 'The Combined Forces', 73, 'Madinah'],
  [34, 'سبأ', 'Saba', 'Sheba', 54, 'Makkah'],
  [35, 'فاطر', 'Fatir', 'Originator', 45, 'Makkah'],
  [36, 'يس', 'Yasin', 'Ya Sin', 83, 'Makkah'],
  [37, 'الصافات', 'As-Saffat', 'Those Who Set The Ranks', 182, 'Makkah'],
  [38, 'ص', 'Sad', 'The Letter Sad', 88, 'Makkah'],
  [39, 'الزمر', 'Az-Zumar', 'The Troops', 75, 'Makkah'],
  [40, 'غافر', 'Ghafir', 'The Forgiver', 85, 'Makkah'],
  [41, 'فصلت', 'Fussilat', 'Explained In Detail', 54, 'Makkah'],
  [42, 'الشورى', 'Ash-Shura', 'The Consultation', 53, 'Makkah'],
  [43, 'الزخرف', 'Az-Zukhruf', 'The Ornaments of Gold', 89, 'Makkah'],
  [44, 'الدخان', 'Ad-Dukhan', 'The Smoke', 59, 'Makkah'],
  [45, 'الجاثية', 'Al-Jathiyah', 'The Crouching', 37, 'Makkah'],
  [46, 'الأحقاف', 'Al-Ahqaf', 'The Wind-Curved Sandhills', 35, 'Makkah'],
  [47, 'محمد', 'Muhammad', 'Muhammad', 38, 'Madinah'],
  [48, 'الفتح', 'Al-Fath', 'The Victory', 29, 'Madinah'],
  [49, 'الحجرات', 'Al-Hujurat', 'The Rooms', 18, 'Madinah'],
  [50, 'ق', 'Qaf', 'The Letter Qaf', 45, 'Makkah'],
  [51, 'الذاريات', 'Adh-Dhariyat', 'The Winnowing Winds', 60, 'Makkah'],
  [52, 'الطور', 'At-Tur', 'The Mount', 49, 'Makkah'],
  [53, 'النجم', 'An-Najm', 'The Star', 62, 'Makkah'],
  [54, 'القمر', 'Al-Qamar', 'The Moon', 55, 'Makkah'],
  [55, 'الرحمن', 'Ar-Rahman', 'The Most Merciful', 78, 'Madinah'],
  [56, 'الواقعة', "Al-Waqi'ah", 'The Inevitable', 96, 'Makkah'],
  [57, 'الحديد', 'Al-Hadid', 'The Iron', 29, 'Madinah'],
  [58, 'المجادلة', 'Al-Mujadila', 'The Pleading Woman', 22, 'Madinah'],
  [59, 'الحشر', 'Al-Hashr', 'The Exile', 24, 'Madinah'],
  [60, 'الممتحنة', 'Al-Mumtahanah', 'She That Is To Be Examined', 13, 'Madinah'],
  [61, 'الصف', 'As-Saff', 'The Ranks', 14, 'Madinah'],
  [62, 'الجمعة', "Al-Jumu'ah", 'Friday', 11, 'Madinah'],
  [63, 'المنافقون', 'Al-Munafiqun', 'The Hypocrites', 11, 'Madinah'],
  [64, 'التغابن', 'At-Taghabun', 'Mutual Disillusion', 18, 'Madinah'],
  [65, 'الطلاق', 'At-Talaq', 'Divorce', 12, 'Madinah'],
  [66, 'التحريم', 'At-Tahrim', 'The Prohibition', 12, 'Madinah'],
  [67, 'الملك', 'Al-Mulk', 'The Sovereignty', 30, 'Makkah'],
  [68, 'القلم', 'Al-Qalam', 'The Pen', 52, 'Makkah'],
  [69, 'الحاقة', 'Al-Haqqah', 'The Reality', 52, 'Makkah'],
  [70, 'المعارج', "Al-Ma'arij", 'The Ascending Stairways', 44, 'Makkah'],
  [71, 'نوح', 'Nuh', 'Noah', 28, 'Makkah'],
  [72, 'الجن', 'Al-Jinn', 'The Jinn', 28, 'Makkah'],
  [73, 'المزمل', 'Al-Muzzammil', 'The Enshrouded One', 20, 'Makkah'],
  [74, 'المدثر', 'Al-Muddaththir', 'The Cloaked One', 56, 'Makkah'],
  [75, 'القيامة', 'Al-Qiyamah', 'The Resurrection', 40, 'Makkah'],
  [76, 'الإنسان', 'Al-Insan', 'Man', 31, 'Madinah'],
  [77, 'المرسلات', 'Al-Mursalat', 'The Emissaries', 50, 'Makkah'],
  [78, 'النبأ', 'An-Naba', 'The Tidings', 40, 'Makkah'],
  [79, 'النازعات', "An-Nazi'at", 'Those Who Drag Forth', 46, 'Makkah'],
  [80, 'عبس', 'Abasa', 'He Frowned', 42, 'Makkah'],
  [81, 'التكوير', 'At-Takwir', 'The Overthrowing', 29, 'Makkah'],
  [82, 'الإنفطار', 'Al-Infitar', 'The Cleaving', 19, 'Makkah'],
  [83, 'المطففين', 'Al-Mutaffifin', 'The Defrauding', 36, 'Makkah'],
  [84, 'الإنشقاق', 'Al-Inshiqaq', 'The Sundering', 25, 'Makkah'],
  [85, 'البروج', 'Al-Buruj', 'The Mansions of the Stars', 22, 'Makkah'],
  [86, 'الطارق', 'At-Tariq', 'The Nightcomer', 17, 'Makkah'],
  [87, 'الأعلى', "Al-A'la", 'The Most High', 19, 'Makkah'],
  [88, 'الغاشية', 'Al-Ghashiyah', 'The Overwhelming', 26, 'Makkah'],
  [89, 'الفجر', 'Al-Fajr', 'The Dawn', 30, 'Makkah'],
  [90, 'البلد', 'Al-Balad', 'The City', 20, 'Makkah'],
  [91, 'الشمس', 'Ash-Shams', 'The Sun', 15, 'Makkah'],
  [92, 'الليل', 'Al-Layl', 'The Night', 21, 'Makkah'],
  [93, 'الضحى', 'Ad-Duha', 'The Morning Hours', 11, 'Makkah'],
  [94, 'الشرح', 'Ash-Sharh', 'The Relief', 8, 'Makkah'],
  [95, 'التين', 'At-Tin', 'The Fig', 8, 'Makkah'],
  [96, 'العلق', "Al-'Alaq", 'The Clot', 19, 'Makkah'],
  [97, 'القدر', 'Al-Qadr', 'The Power', 5, 'Makkah'],
  [98, 'البينة', 'Al-Bayyinah', 'The Clear Proof', 8, 'Madinah'],
  [99, 'الزلزلة', 'Az-Zalzalah', 'The Earthquake', 8, 'Madinah'],
  [100, 'العاديات', "Al-'Adiyat", 'The Courser', 11, 'Makkah'],
  [101, 'القارعة', "Al-Qari'ah", 'The Calamity', 11, 'Makkah'],
  [102, 'التكاثر', 'At-Takathur', 'The Rivalry in World Increase', 8, 'Makkah'],
  [103, 'العصر', "Al-'Asr", 'The Declining Day', 3, 'Makkah'],
  [104, 'الهمزة', 'Al-Humazah', 'The Traducer', 9, 'Makkah'],
  [105, 'الفيل', 'Al-Fil', 'The Elephant', 5, 'Makkah'],
  [106, 'قريش', 'Quraysh', 'Quraysh', 4, 'Makkah'],
  [107, 'الماعون', "Al-Ma'un", 'The Small Kindnesses', 7, 'Makkah'],
  [108, 'الكوثر', 'Al-Kawthar', 'The Abundance', 3, 'Makkah'],
  [109, 'الكافرون', 'Al-Kafirun', 'The Disbelievers', 6, 'Makkah'],
  [110, 'النصر', 'An-Nasr', 'The Divine Support', 3, 'Madinah'],
  [111, 'اللهب', 'Al-Lahab', 'The Flame', 5, 'Makkah'],
  [112, 'الإخلاص', 'Al-Ikhlas', 'The Sincerity', 4, 'Makkah'],
  [113, 'الفلق', 'Al-Falaq', 'The Daybreak', 5, 'Makkah'],
  [114, 'الناس', 'An-Nas', 'Mankind', 6, 'Makkah'],
];

export const SURAHS: SurahMeta[] = RAW.map(([number, arabic, transliteration, english, ayahs, place]) => ({
  number,
  arabic,
  transliteration,
  english,
  ayahs,
  place,
}));

export function getSurah(n: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.number === n);
}

export const QURAN_TRANSLATION_SOURCE = 'BASIRA Simple English rendering of the Arabic (public domain)';
export const QURAN_INTEGRATION_NOTE =
  'Reading mode connects to an external Quran dataset (api.alquran.cloud) for the full text with the Pickthall translation (public domain, 1930). When the external source cannot be reached, BASIRA shows its curated verified ayah collection instead and clearly says so.';
