import type { SeedRecord } from './shared';

// ============================================================================
// FIQH — educational guides, clearly labeled: compiled explanations based on
// authentic sources, presenting school differences respectfully. NOT fatwas.
// Where a difference of opinion exists between recognized schools, it is
// shown as such — never flattened into one invented "answer".
// ============================================================================

const FG = { sourceType: 'FIQH', verificationStatus: 'VERIFIED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15' } as const;
const NOTE = 'Educational summary compiled from the Qur\'an, the Sunnah, and the standard positions of the four recognized schools. BASIRA is an educational tool — not a fatwa service. For your specific situation, please consult a qualified local scholar.';

export const FIQH_SEED: SeedRecord[] = [
  {
    slug: 'fiqh-wudu-steps', title: 'How to perform wudu (ablution)',
    category: 'wudu',
    englishText: 'Wudu (ablution) is the purification required before prayer. The Qur\'an itself defines its essential parts (5:6), and the Prophet ﷺ demonstrated them — transmitted precisely by companions like Uthman ibn Affan (Sahih al-Bukhari, Book of Ablution; Sahih Muslim 226).',
    explanation: 'Everything below is established by the Qur\'an 5:6 and the Prophetic practice narrated in Bukhari and Muslim. Differences between the schools are minor and noted where relevant.',
    practicalSteps: [
      'Make the intention in your heart to purify for Allah (the intention hadith: Bukhari 1).',
      'Say "Bismillah" (recorded in the collections with sound grades).',
      'Wash both hands three times.',
      'Rinse the mouth three times, then rinse the nose three times (together per some narrations, separately per others — both valid).',
      'Wash the face three times (from hairline to chin, ear to ear).',
      'Wash the right arm to the elbow three times, then the left.',
      'Wipe the head once (ears included per the majority narration of Bukhari/Muslim).',
      'Wash the right foot to the ankle three times, then the left.',
      'Finish, facing the qiblah is not required — simply say: "Ashhadu an la ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan \'abduhu wa rasuluh" (Sahih Muslim 234).',
    ],
    referenceNote: NOTE,
    topics: 'wudu, purity, prayer, salah, beginner', keywords: 'ablution, wash, purification, how to, steps', ...FG,
  },
  {
    slug: 'fiqh-wudu-breaks', title: 'What breaks wudu — and where schools differ',
    category: 'wudu',
    englishText: 'Acts agreed to nullify wudu (based on the Qur\'an 4:43, 5:6, and mass-transmitted Sunnah): anything exiting from the two private passages (urine, stool, wind), deep sleep (losing consciousness), and according to the majority: loss of intellect through fainting or intoxication.',
    explanation: 'Scholars have differed on some matters — BASIRA shows the recognized positions rather than inventing a single answer: (1) Touching a woman\'s skin: the Shafi\'i school holds it nullifies wudu (based on their reading of 4:43 "or you have touched women"); the Hanafi, Maliki, and Hanbali schools hold it does not, understanding the verse about intercourse — follow your school or consult a scholar. (2) Touching the private parts directly: nullifies per the Shafi\'i and Hanbali reading of the hadith; does not per the Hanafi school (another narration supports them). (3) Bleeding: the classical Hanafi position nullifies for flowing blood; others do not treat it as a nullifier. (4) Vomiting: differences exist on the amount. All four schools are respected; this list reflects their classical manuals.',
    referenceNote: NOTE,
    topics: 'wudu, purity, differences', keywords: 'breaks wudu, nullifies, touch, bleeding, sleep', ...FG,
  },
  {
    slug: 'fiqh-ghusl', title: 'How to perform ghusl (full purification)',
    category: 'ghusl',
    englishText: 'Ghusl is the full-body purification required after sexual discharge, the completion of menses, and before Jumu\'ah (recommended) — commanded by Qur\'an 4:43 for major impurity.',
    explanation: 'The Prophet\'s ﷺ demonstrated ghusl (recorded by Bukhari and Muslim from Aisha and Maymuna):',
    practicalSteps: [
      'Make the intention for ghusl.',
      'Wash both hands, then the private area (removing any impurity).',
      'Perform full wudu (some narrations delay the feet to the end).',
      'Pour water over the head three times, rubbing so it reaches the roots of the hair.',
      'Pour water over the entire body, right side then left, rubbing all folds.',
      'The obligatory parts per the majority: rinsing the mouth and nose, and water over all of the skin — missing any part requires repeating it.',
    ],
    referenceNote: NOTE,
    topics: 'ghusl, purity, janabah, jumuah', keywords: 'bath, full purification, ghusl, major impurity', ...FG,
  },
  {
    slug: 'fiqh-tayammum', title: 'Tayammum — purification without water',
    category: 'wudu',
    englishText: 'When water is unavailable, or harmful (illness, extreme cold), the Qur\'an itself legislates tayammum: "…then seek clean earth and wipe your faces and hands with it" (Qur\'an 5:6).',
    explanation: 'The Prophet ﷺ said the earth has been made a place of prayer and purification for his Ummah (Bukhari). Strike clean earth with the palms, wipe the face, then wipe the hands. It expires with the same things that break wudu, or when water becomes available (before praying, per most schools).',
    referenceNote: NOTE,
    topics: 'wudu, tayammum, purity, travel, illness', keywords: 'dry ablution, earth, no water, travel', ...FG,
  },
  {
    slug: 'fiqh-prayer-times-overview', title: 'The five daily prayers — names and times',
    category: 'salah-times',
    englishText: 'Five obligatory prayers, "decreed upon the believers at specified times" (Qur\'an 4:103): Fajr, Dhuhr, Asr, Maghrib, and Isha. Their times were taught by the Prophet ﷺ and are anchored in the movement of the sun.',
    explanation: 'Fajr: from true dawn to sunrise. Dhuhr: after the sun passes its zenith until Asr. Asr: when an object\'s shadow equals its length plus noon shadow (majority schools) or twice its length (Hanafi) until sunset. Maghrib: immediately after sunset until the red twilight fades (Hanafi extends to full darkness). Isha: from then until (half the night / a third / dawn — jurists differ on the preferred end). BASIRA\'s prayer-time engine lets you choose the calculation method and Asr factor.',
    referenceNote: NOTE,
    topics: 'prayer, salah, prayer times, fajr, dhuhr, asr, maghrib, isha', keywords: 'times, schedule, when to pray, five prayers', ...FG,
  },
  {
    slug: 'fiqh-how-to-pray', title: 'How to pray — step by step for beginners',
    category: 'how-to-pray',
    englishText: '"Pray as you have seen me praying" (Sahih al-Bukhari 631). The prayer below is the universally transmitted structure; the notes flag the famous minor differences between schools so you can recognize them respectfully.',
    explanation: 'This is a 2-rakʿah example (Fajr); longer prayers simply add rakʿahs of the same pattern.',
    practicalSteps: [
      'Stand facing the qiblah, make the intention in your heart for the specific prayer.',
      'Raise your hands and say "Allahu Akbar" (the opening takbir). Place the right hand over the left — on the chest (Shafi\'i, Hanbali and one Hanafi narration) or below the navel (classical Hanafi). All positions are respected; within one prayer follow one pattern.',
      'Recite Surah al-Fatihah — required in every rakʿah. Then recite another passage in the first two rakʿahs.',
      'Say "Allahu Akbar" and bow (ruku\'), hands on knees, back level, saying "Subhana Rabbiyal-\'Adhim".',
      'Rise saying "Sami\'a Allahu liman hamidah; Rabbana lakal-hamd."',
      'Say "Allahu Akbar" and prostrate (sujud) on seven limbs: forehead+nose, two palms, two knees, toes of both feet — saying "Subhana Rabbiyal-A\'la" (glorify at least three times).',
      'Sit up saying "Allahu Akbar", sit calmly, then prostrate a second time the same way.',
      'Stand for the second rakʿah saying "Allahu Akbar" (without the opening hands-raising), and repeat.',
      'After its second prostration, sit for tashahhud: recite the greetings to Allah\'s favored servant, then Ibrahim\'s salawat (Bukhari, Muslim). In a 2-rakʿah prayer, conclude here; longer prayers add a middle sitting.',
      'Turn your head right saying "As-salamu \'alaykum wa rahmatullah", then left — the taslim completes the prayer.',
      'Then the after-prayer dhikr: istighfar x3, "Allahumma antas-Salam…" and 33-33-33-1 (Muslim 591, 597).',
    ],
    referenceNote: NOTE,
    topics: 'prayer, salah, how to pray, beginner, rakah', keywords: 'how to pray, steps, learn salah, beginner, takbir, ruku, sujud, tashahhud', ...FG,
  },
  {
    slug: 'fiqh-prayer-invalidators', title: 'What invalidates the prayer',
    category: 'salah-rulings',
    englishText: 'Agreed invalidators based on the narrations: leaving a pillar (e.g., forgetting the Fatihah or the final tashahhud), deliberate invalid speech, excessive unrelated movement, eating or drinking, losing purification (wudu breaking) mid-prayer, and turning the chest away from the qiblah.',
    explanation: 'If invalidated, the prayer is repeated calmly — no sin attaches to an unintentional mistake. The Prophet ﷺ ordered the forgetful one to rebuild rather than abandon (the hadith of the poor-praying man, Bukhari 757, with "go back and pray, for you have not prayed"). Walking in front of a praying person is a sin for the walker, not the pray-er (per the mass-narrated threat of the Prophet ﷺ); the schools differ on what barrier height is needed.',
    referenceNote: NOTE,
    topics: 'prayer, salah, invalidators, mistakes', keywords: 'invalid, breaks prayer, annuls, void', ...FG,
  },
  {
    slug: 'fiqh-prayer-mistakes', title: 'Common prayer mistakes to fix gently',
    category: 'salah-rulings',
    englishText: 'Gentle corrections of habits seen in many mosques — each traceable to a narration:',
    explanation: 'None of these make someone a "bad Muslim" — they are refinements.',
    practicalSteps: [
      'Rushing the ruku\' and sujud: the Prophet ﷺ ordered calm in every posture ("then be calm in it" — Bukhari).',
      'Looking around: "the prayer is not accepted while looking around" (recorded with sound grades) — eyes on the place of sujud.',
      'Reciting Fatihah too fast: recite with measured tone — the Qur\'an was revealed to be recited slowly and beautifully.',
      'Standing up before the imam finishes "Allahu Akbar": "the imam is there to be followed" (mass-narrated).',
      'Skipping the two sunnah rakʿahs of Fajr: they are "better than the world and all it contains" (Muslim 725).',
      'Playing with clothes or phone during prayer: counted as fidgeting the Prophet ﷺ forbade ("be still in prayer").',
      'After taslim, leaving instantly: the Prophet ﷺ remained sitting for the dhikr — a minute of istighfar and tasbih transforms the whole prayer\'s afterglow.',
    ],
    referenceNote: NOTE,
    topics: 'prayer, salah, mistakes, manners', keywords: 'common mistakes, rushing, calm, attention, fix', ...FG,
  },
  {
    slug: 'fiqh-missed-prayer', title: 'What to do if you missed a prayer',
    category: 'salah-rulings',
    englishText: 'If you FORGOT or overslept: pray it immediately when you remember — "whoever forgets a prayer should pray it when he remembers it; there is no expiation except that" (Sahih al-Bukhari 597). No guilt ritual exists in Islam for forgetting.',
    explanation: 'If you DELIBERATELY missed it: scholars teach you must repent to Allah (tawbah — see the Repentance guide) and make the prayer up (qada\') as soon as possible. For long periods of abandoned prayers, consult a qualified scholar — the schools differ on whether missed prayers are made up individually or remedied by present repentance and steadfastness. BASIRA deliberately does not issue one blanket ruling here: this is a real matter of juristic discussion. For chronic cases, a trusted local scholar is the right address.',
    referenceNote: NOTE,
    topics: 'prayer, salah, missed prayer, qada, repentance', keywords: 'missed salah, forgot, oversleep, make up, qada', ...FG,
  },
  {
    slug: 'fiqh-jumuah-sunnahs', title: 'The Sunnahs of Friday (Jumu\'ah)',
    category: 'jumuah',
    englishText: 'Bukhari\'s Book of Friday preserves the full etiquette: ghusl, best clothes, fragrance, early arrival, no stepping over people, the sunnah prayers, and total silence during the khutbah — "whoever does this, Allah forgives what is between the two Fridays."',
    explanation: 'Additional recommended practices: sending abundant salawat upon the Prophet ﷺ during the day (per narrations graded differently by scholars); reciting Surah al-Kahf (DISPUTED grading — see the Hadith section where BASIRA shows the scholarly discussion transparently); arriving early (the earlier hours are likened to sacrificing a camel, then a cow, then a ram); and giving charity on the day.',
    referenceNote: NOTE,
    topics: 'jumuah, friday, sunnah, prayer', keywords: 'friday sunnahs, ghusl, khutbah, early, kahf', ...FG,
  },
  {
    slug: 'fiqh-witr-positions', title: 'Witr — how the schools pray it',
    category: 'witr',
    englishText: 'Witr is a strongly recommended night prayer — the Prophet ﷺ said: "Allah has given you an additional prayer: al-Witr — pray it between Isha and Fajr" (Sunan Abi Dawud 1416, graded sahih). He never left it, at home or traveling.',
    explanation: 'The schools differ on details, all respectfully valid: The Hanafi school treats witr as three rakʿahs with one salam (near-obligatory in their view, prayed like Maghreb but with a second tashahhud — without calling it "Maghreb-like" in intention). The Shafi\'i and Hanbali schools hold the minimum is one rakʿah and prefer three (separated or joined); they also permit five, seven, and more odd numbers — "Witr is odd rakʿahs" per the sound narrations. The Maliki school prays three joined with one salam. All agree: never pray witr twice in a night, and the Prophet\'s ﷺ practice varied to teach permissibility.',
    referenceNote: NOTE,
    topics: 'witr, prayer, salah, differences, night prayer', keywords: 'witr, odd, night, three rakahs, one rakah', ...FG,
  },
  {
    slug: 'fiqh-tawbah-steps', title: 'How to make tawbah (repentance) — step by step',
    category: 'tawbah',
    englishText: 'Tawbah is returning to Allah. The Qur\'an commands it and promises acceptance: "Do not despair of Allah\'s mercy; surely Allah forgives all sins" (39:53); "Allah loves those who repent" (2:222). The Prophet ﷺ said every son of Adam errs, and the best of those who err are those who repent (Tirmidhi 2499).',
    explanation: 'The conditions are drawn from the classical manuals and the Qur\'anic verses on repentance:',
    practicalSteps: [
      'Stop the sin immediately.',
      'Feel genuine remorse — "the Prophet ﷺ said remorse is repentance" (recorded by Ibn Majah and Ahmad, graded hasan by some scholars).',
      'Resolve not to return to it.',
      'If the sin involved another person\'s rights: restore their right or seek their pardon.',
      'If the sin involved missed obligations (prayers, zakat): begin making them up — see the missed-prayer guide.',
      'Ask with the Prophetic words: astaghfirullah (70-100 times daily was the Prophet\'s ﷺ practice, Bukhari 6307) and the Sayyid al-Istighfar (Bukhari 6306).',
      'Do not despair between attempts: "Allah rejoices at the repentance of His servant more than a man who finds his lost camel" (Muslim 2747).',
    ],
    referenceNote: NOTE,
    topics: 'tawbah, repentance, forgiveness, sin', keywords: 'repent, tawbah, tauba, sin, return, forgiveness, how to', ...FG,
  },
  {
    slug: 'fiqh-zakat-basics', title: 'Zakat basics — the purification of wealth',
    category: 'zakat',
    englishText: 'Zakat is the third pillar of Islam (Bukhari 8): an annual due of 2.5% on qualifying wealth held for one lunar year at or above the nisab (the threshold ≈ 85g of gold / 595g of silver in value).',
    explanation: 'Recipients are defined by Qur\'an 9:60 (the eight categories). Gold, silver, cash, business inventory, and livestock are zakatable; debts owed reduce the base. Special cases — retirement funds, crypto, business partnerships, agricultural produce rates (a tenth/half-tenth depending on irrigation) — carry juristic detail: BASIRA gives the framework and recommends a qualified scholar or trusted calculator for exact figures. Zakat is worship, not taxation — it purifies the remaining wealth (Qur\'an 9:103).',
    referenceNote: NOTE,
    topics: 'zakat, charity, wealth, pillars', keywords: 'zakah, nisab, 2.5, gold, silver, calculate', ...FG,
  },
  {
    slug: 'fiqh-fasting-basics', title: 'Fasting essentials',
    category: 'ramadan',
    englishText: 'Fasting Ramadan is the fourth pillar (Bukhari 8): abstaining from food, drink, and marital intimacy from true dawn to sunset with the intention — "so that you may become mindful of God" (2:183).',
    explanation: 'The fast is voided by deliberate eating, drinking, sexual intercourse, deliberate vomiting, and — per the majority — the exit of semen with desire. Unintentional eating does not break the fast ("continue your fast — it was only Allah who fed you" per the agreed narration). Travelers and the ill may defer the day (2:184); menses obligates making days up later; the elderly who cannot fast feed a poor person per meal. Suhoor is blessed ("eat suhour, for in suhoor is blessing" — Bukhari/Muslim); breaking fast promptly at sunset is Sunnah; the fasting person\'s dua at iftar is cherished. Nights of Ramadan: Tarawih in congregation (see its history in the Hadith section) and seeking Laylat al-Qadr in the odd nights of the last ten (Bukhari 2017).',
    referenceNote: NOTE,
    topics: 'ramadan, fasting, sawm', keywords: 'fast, siyam, ramadhan, suhoor, iftar, break fast', ...FG,
  },
  {
    slug: 'fiqh-halal-earning', title: 'Halal earning and spending',
    category: 'business',
    englishText: 'The Qur\'an permits trade by mutual consent and forbids consuming wealth unjustly (4:29); the Prophet ﷺ warned that flesh nourished by haram gains is more deserving of the Fire (recorded in the collections). Honest trade is worship: the truthful, trustworthy merchant is with the prophets (Tirmidhi 1209).',
    explanation: 'Established principles: no riba (interest/usury — Qur\'an 2:275-279); no gharar (deceptive uncertainty — "the Prophet ﷺ forbade selling what is not present" per the sound narrations); full disclosure — "whoever deceives us is not one of us" (Muslim 102); salaries must be prompt — "give the worker his wage before his sweat dries" (graded hasan by some scholars); and contracts need clear offer and acceptance ("the two parties have the choice until they separate" — Bukhari 2079). Modern instruments (stocks, insurance, mortgages) require case-by-case scholarship — consult a qualified scholar; BASIRA provides the framework only.',
    referenceNote: NOTE,
    topics: 'business, trade, halal, earning, finance', keywords: 'halal, haram, riba, interest, trade, business, salary, money', ...FG,
  },
  {
    slug: 'fiqh-beginner-path', title: 'Your first week as a praying Muslim',
    category: 'beginner',
    englishText: 'A gentle onboarding path for the newly practicing — Islam is gradual, "the religion is ease" (Sahih al-Bukhari, Book of Belief).',
    explanation: 'BASIRA recommends patience with yourself: the Prophet\'s ﷺ Companions took years to learn the full law; you are allowed weeks.',
    practicalSteps: [
      'Day 1-2: Learn wudu (see the wudu guide) and the movements of prayer.',
      'Day 3-5: Pray one prayer fully (start with Dhuhr — it is mid-day and simple), then add one prayer each day.',
      'Week 1 end: aim for all five, even if recitation is slow and mistakes happen — "the one who recites the Qur\'an with difficulty has twice the reward" (agreed upon).',
      'Week 2: add the two sunnah rakʿahs of Fajr and the after-prayer dhikr (33-33-33-1).',
      'Ongoing: 5 minutes of daily Qur\'an with meaning; the morning/evening adhkar; and say "Salla Allahu \'alayhi wa sallam" whenever the Prophet\'s ﷺ name appears.',
      'Find a teacher or a local mosque class — the religion is learned hand-to-hand, generation to generation.',
    ],
    referenceNote: NOTE,
    topics: 'beginner, prayer, salah, new muslim, guidance', keywords: 'beginner, start, first week, new muslim, convert, learn', ...FG,
  },
];
