import type { SeedRecord } from './shared';

// ============================================================================
// GLOSSARY — beginner-friendly Islamic terms. Simple explanations that do
// not assume prior knowledge (Beginner Mode's backbone).
// ============================================================================

const G = { sourceType: 'GLOSSARY', verificationStatus: 'VERIFIED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15' } as const;

export const GLOSSARY_SEED: SeedRecord[] = [
  {
    slug: 'glossary-salah', title: 'Salah', category: 'worship',
    arabicText: 'الصَّلاَة',
    englishText: 'The five daily obligatory prayers of Islam — the direct link between a Muslim and Allah. Performed at set times facing the qiblah (Makkah): Fajr (dawn, 2 rakʿahs), Dhuhr (noon, 4), Asr (afternoon, 4), Maghrib (sunset, 3), and Isha (night, 4).',
    explanation: '"Establish prayer for My remembrance" (Qur\'an 20:14). See BASIRA\'s Prayer section for full step-by-step guides.',
    topics: 'prayer, salah, worship, beginner', keywords: 'namaz, prayer, salat, worship', ...G,
  },
  {
    slug: 'glossary-wudu', title: 'Wudu', category: 'purity',
    arabicText: 'الوُضُوء',
    englishText: 'The washing purification (face, arms, head, feet) performed before prayer. Defined by the Qur\'an (5:6) and demonstrated by the Prophet ﷺ. Takes under a minute.',
    explanation: '"Allah does not intend to place you in difficulty, but to purify you and complete His favor upon you" (end of 5:6).',
    topics: 'wudu, purity, prayer, beginner', keywords: 'ablution, wash, purification', ...G,
  },
  {
    slug: 'glossary-ghusl', title: 'Ghusl', category: 'purity',
    arabicText: 'الغُسْل',
    englishText: 'The full-body bath required after sexual discharge or the end of menses, and recommended before Friday prayer.',
    explanation: 'See the Fiqh guide "How to perform ghusl" for the Prophetic steps.',
    topics: 'ghusl, purity', keywords: 'bath, full purification, janabah', ...G,
  },
  {
    slug: 'glossary-zakat', title: 'Zakat', category: 'finance',
    arabicText: 'الزَّكَاة',
    englishText: 'The obligatory annual charity of 2.5% on qualifying wealth held for a year — the third pillar of Islam. Purifies wealth and guarantees society\'s poorest a share.',
    explanation: 'Recipients are fixed by Qur\'an 9:60. See "Zakat basics" in the Fiqh section.',
    topics: 'zakat, charity, wealth, beginner', keywords: 'zakah, charity, poor, 2.5, nisab', ...G,
  },
  {
    slug: 'glossary-ramadan', title: 'Ramadan', category: 'time',
    arabicText: 'رَمَضَان',
    englishText: 'The ninth month of the Hijri calendar, in which the Qur\'an was first sent down. Muslims fast from true dawn to sunset — the fourth pillar — and increase prayer, Qur\'an, and charity. The month ends with Eid al-Fitr.',
    explanation: '"Whoever fasts Ramadan with faith and seeking reward, his previous sins are forgiven" (Bukhari 38). Its start and end follow the moon sighting, so dates differ by country.',
    topics: 'ramadan, fasting, beginner, time', keywords: 'fasting month, ramadhan, sawm', ...G,
  },
  {
    slug: 'glossary-tawbah', title: 'Tawbah', category: 'spirituality',
    arabicText: 'التَّوْبَة',
    englishText: 'Repentance — literally "returning." Stopping a sin, feeling remorse, resolving not to return, and restoring others\' rights if any were harmed.',
    explanation: '"Do not despair of Allah\'s mercy — surely Allah forgives all sins" (39:53). See "How to make tawbah" in the Fiqh section for the full steps.',
    topics: 'tawbah, repentance, forgiveness, beginner', keywords: 'repentance, tauba, return, sin', ...G,
  },
  {
    slug: 'glossary-sunnah', title: 'Sunnah', category: 'sources',
    arabicText: 'السُّنَّة',
    englishText: 'The way of the Prophet Muhammad ﷺ — everything he said, did, and approved, carefully transmitted by his companions. Also used for recommended (non-obligatory) actions, e.g. "the Sunnah prayers".',
    explanation: 'Following the Sunnah is following the Qur\'an\'s command to obey the Messenger ﷺ; the Prophet ﷺ said "whoever lies about me deliberately, let him take his seat in the Fire" (Bukhari 110) — which is why preservation was so rigorous.',
    topics: 'sunnah, sources, hadith, beginner', keywords: 'prophetic way, practice, tradition', ...G,
  },
  {
    slug: 'glossary-hadith', title: 'Hadith', category: 'sources',
    arabicText: 'الحَدِيث',
    englishText: 'A report of something the Prophet ﷺ said, did, or approved — transmitted through a named chain of narrators (isnad). Collections like Sahih al-Bukhari verified these chains with unmatched historical rigor.',
    explanation: 'A hadith has a matn (text) and an isnad (chain). The science of hadith grades reports as sahih (authentic), hasan (sound), or daʿif (weak) — see the individual entries.',
    topics: 'hadith, sources, beginner', keywords: 'narration, report, tradition, hadiths', ...G,
  },
  {
    slug: 'glossary-sahih', title: 'Sahih', category: 'sources',
    arabicText: 'صَحِيح',
    englishText: '"Authentic" — the highest grade of hadith: an unbroken, upright, precise chain with a text free of defects. Sahih al-Bukhari and Sahih Muslim (the "Two Sahihs") contain the most rigorously verified reports.',
    explanation: 'Sahih al-Bukhari: Imam Muhammad ibn Isma\'il al-Bukhari (810-870 CE) reportedly verified each hadith by praying before recording it; the collection is the most authoritative book after the Qur\'an.',
    topics: 'hadith, sources, grading', keywords: 'authentic, sahih, bukhari, grading', ...G,
  },
  {
    slug: 'glossary-daif', title: 'Daʿif', category: 'sources',
    arabicText: 'ضَعِيف',
    englishText: '"Weak" — a hadith whose chain has a gap, an unreliable narrator, or a defect. Scholars differ over when weak narrations may be cited (virtues of deeds vs. law). BASIRA marks disputed/pending material transparently.',
    explanation: 'Between sahih and daʿif is hasan ("good/sound") — reliable for practice. This is why BASIRA never presents a claim as "authentic" without its grade.',
    topics: 'hadith, sources, grading', keywords: 'weak, grading, isnad', ...G,
  },
  {
    slug: 'glossary-madhhab', title: 'Madhhab', category: 'fiqh',
    arabicText: 'مَذْهَب',
    englishText: 'A recognized school of Islamic jurisprudence — a structured methodology of deriving rulings from the Qur\'an and Sunnah. The four Sunni schools: Hanafi, Maliki, Shafi\'i, and Hanbali (named after their founding imams).',
    explanation: 'The schools agree on the fundamentals and differ on details — historically with deep mutual respect. BASIRA shows their positions side by side rather than claiming one universal answer. Following a school is customary for most Muslims, but selecting one is optional in BASIRA (your profile has "no preference" by default).',
    topics: 'madhhab, fiqh, differences, beginner', keywords: 'school, hanafi, shafii, maliki, hanbali, jurisprudence', ...G,
  },
  {
    slug: 'glossary-fiqh', title: 'Fiqh', category: 'fiqh',
    arabicText: 'الفِقْه',
    englishText: 'Islamic jurisprudence — the human scholarly discipline of deriving practical rulings (worship, transactions, family, etc.) from the revealed sources. A faqih is a qualified jurist.',
    explanation: 'Fiqh means "deep understanding." It is not the Qur\'an itself, nor a single voice: it is a rich scholarly tradition with methodologies and respected differences.',
    topics: 'fiqh, jurisprudence, beginner', keywords: 'jurisprudence, law, rulings, understanding', ...G,
  },
  {
    slug: 'glossary-tawhid', title: 'Tawhid', category: 'aqeedah',
    arabicText: 'التَّوْحِيد',
    englishText: 'The Oneness of Allah — the central belief of Islam: Allah is one in His lordship, His worship, and His names and attributes. The opposite is shirk: associating partners with Allah.',
    explanation: '"Say: He is Allah, the One" (Qur\'an 112). The first half of the Shahada is its declaration.',
    topics: 'tawhid, aqeedah, belief, beginner', keywords: 'oneness, monotheism, shirk, allah', ...G,
  },
  {
    slug: 'glossary-iman', title: 'Iman', category: 'aqeedah',
    arabicText: 'الإِيمَان',
    englishText: 'Faith — belief in the heart, affirmation by the tongue, and action of the limbs. Its six articles (from the Hadith of Jibril, Bukhari 50): Allah, His angels, His books, His messengers, the Last Day, and divine decree.',
    explanation: 'Iman rises and falls with deeds — the Prophet ﷺ said none of you believes until he loves for his brother what he loves for himself (Bukhari 13).',
    topics: 'iman, faith, aqeedah, beginner', keywords: 'belief, faith, articles', ...G,
  },
  {
    slug: 'glossary-ihsan', title: 'Ihsan', category: 'aqeedah',
    arabicText: 'الإِحْسَان',
    englishText: 'Excellence in worship — "to worship Allah as though you see Him; for if you do not see Him, He surely sees you" (the Prophet ﷺ to Jibril, Bukhari 50). The highest level of religion.',
    explanation: 'Ihsan also means beautiful conduct with people — the Qur\'an commands "justice and ihsan" together (16:90).',
    topics: 'ihsan, excellence, aqeedah', keywords: 'excellence, god-consciousness, character', ...G,
  },
  {
    slug: 'glossary-jannah', title: 'Jannah', category: 'hereafter',
    arabicText: 'الجَنَّة',
    englishText: 'Paradise — the eternal home of the righteous: gardens beneath which rivers flow (Qur\'an 2:25), and joys "no eye has seen, no ear has heard, nor entered the heart of man" (Bukhari 7498).',
    explanation: 'Its lowest ranks outshine this entire world; its highest is seeing Allah. Entered by Allah\'s mercy through faith and righteous deeds.',
    topics: 'jannah, paradise, hereafter, beginner', keywords: 'paradise, heaven, garden, reward', ...G,
  },
  {
    slug: 'glossary-jahannam', title: 'Jahannam', category: 'hereafter',
    arabicText: 'جَهَنَّمَ',
    englishText: 'Hell — the place of purification and justice for those who earned it by evil and rejection of truth after it reached them. Allah\'s mercy "encompasses all things" and He forgives all sins for those who return (39:53).',
    explanation: 'The Prophet ﷺ warned of the Fire out of mercy, not to terrorize: his way was "give good news and make things easy" (agreed upon in the narrations). BASIRA shares warnings exactly as the sources state them — no more, no less.',
    topics: 'jahannam, hell, hereafter', keywords: 'hell, fire, punishment, warning', ...G,
  },
  {
    slug: 'glossary-quran-term', title: 'Qur\'an', category: 'sources',
    arabicText: 'القُرْآن',
    englishText: 'The literal word of Allah, revealed to the Prophet Muhammad ﷺ over 23 years, preserved letter-for-letter by mass transmission and memorization, and recited in daily prayer. 114 surahs (chapters).',
    explanation: '"A blessed Book We sent down to you, that they may reflect upon its verses" (38:29). The best of you are those who learn it and teach it (Bukhari 5027).',
    topics: 'quran, sources, beginner', keywords: 'koran, quran, revelation, book', ...G,
  },
  {
    slug: 'glossary-dua', title: 'Duʿa', category: 'worship',
    arabicText: 'الدُّعَاء',
    englishText: 'Supplication — calling upon Allah directly, in any language, at any time. "Your Lord has said: Call upon Me; I will answer you" (Qur\'an 40:60). Du\'a itself is worship.',
    explanation: 'The etiquette: begin with praise, send salawat, ask with certainty and patience. The Dua library organizes the narrated duas by situation — labeled Sunnah vs. general permissible.',
    topics: 'dua, worship, supplication', keywords: 'supplication, asking, prayer, dua', ...G,
  },
  {
    slug: 'glossary-dhikr', title: 'Dhikr', category: 'worship',
    arabicText: 'الذِّكْر',
    englishText: 'Remembrance of Allah — phrases like SubhanAllah, Alhamdulillah, Allahu Akbar, La ilaha illallah, and recitation of the Qur\'an. "Surely in the remembrance of Allah do hearts find rest" (13:28).',
    explanation: 'The Dhikr section provides the authentic morning/evening/after-prayer remembrances with their established counts — never invented.',
    topics: 'dhikr, remembrance, worship', keywords: 'remembrance, zhikr, tasbih, remembering', ...G,
  },
  {
    slug: 'glossary-seerah', title: 'Seerah', category: 'history',
    arabicText: 'السِّيرَة',
    englishText: 'The biography of the Prophet Muhammad ﷺ — his life, character, and missions, preserved in classical works like Ibn Ishaq/Ibn Hisham and the hadith collections.',
    explanation: 'BASIRA\'s Seerah timeline marks each event\'s source; reports of weaker or debated authenticity are labeled, never presented as certain history.',
    topics: 'seerah, history, prophet', keywords: 'biography, prophet life, sirah', ...G,
  },
  {
    slug: 'glossary-fitrah', title: 'Fitrah', category: 'aqeedah',
    arabicText: 'الفِطْرَة',
    englishText: 'The innate nature every human is born upon — naturally inclined toward Allah and good, before environment shapes them.',
    explanation: 'The bedtime dua ends: "if you die tonight, you die upon the fitrah" (Bukhari 247). Islam sees itself as the restoration of this original nature, not a foreign imposition.',
    topics: 'fitrah, nature, belief', keywords: 'innate, nature, disposition', ...G,
  },
  {
    slug: 'glossary-qiblah', title: 'Qiblah', category: 'worship',
    arabicText: 'القِبْلَة',
    englishText: 'The direction of prayer: the Kaʿbah in Makkah. Muslims worldwide unite facing one point five times a day.',
    explanation: 'Changed from Jerusalem to Makkah in the Prophet\'s ﷺ second year in Madinah (Qur\'an 2:144).',
    topics: 'qibla, prayer, worship', keywords: 'direction, makkah, kaaba, ka\'bah', ...G,
  },
  {
    slug: 'glossary-adhan', title: 'Adhan', category: 'worship',
    arabicText: 'الأَذَان',
    englishText: 'The call to prayer, announced at each prayer time. The iqamah is the second, shorter call made immediately before the congregational prayer begins.',
    explanation: 'Established in the first year in Madinah; whoever says after the adhan "I am pleased that Allah is my Lord…" has his sins forgiven (Sahih Muslim 386 — the twin of the adhan\'s phrases).',
    topics: 'adhan, prayer, worship', keywords: 'call to prayer, azan, iqamah', ...G,
  },
  {
    slug: 'glossary-rakah', title: 'Rakʿah', category: 'worship',
    arabicText: 'رَكْعَة',
    englishText: 'One full cycle of prayer: standing with Fatihah + recitation, bowing (ruku\'), and two prostrations (sujud) with a sitting between.',
    explanation: 'Prayers are composed of 2-4 rakʿahs; the word comes from ruku\' (bowing).',
    topics: 'prayer, salah, rakah', keywords: 'cycle, unit, rakat, rakah', ...G,
  },
  {
    slug: 'glossary-shahadah', title: 'Shahadah', category: 'aqeedah',
    arabicText: 'الشَّهَادَة',
    englishText: 'The testimony of faith — "Ash-hadu an la ilaha illallah, wa ash-hadu anna Muhammadar-Rasulullah": I bear witness that there is no god but Allah and that Muhammad is the Messenger of Allah. The first pillar and the entry door of Islam.',
    explanation: 'Said with conviction, it makes a person a Muslim. Everything else in Islam builds on this testimony.',
    topics: 'shahadah, faith, pillars, beginner', keywords: 'testimony, declaration, conversion, kalimah', ...G,
  },
  {
    slug: 'glossary-tawakkul', title: 'Tawakkul', category: 'spirituality',
    arabicText: 'التَّوَكُّل',
    englishText: 'Reliance on Allah — entrusting outcomes to Him while taking every legitimate means. "Whoever places his trust in Allah, He is enough for him" (65:3).',
    explanation: 'The Prophet ﷺ taught tying the camel AND trusting in Allah (graded hasan in Tirmidhi). Tawakkul is not passivity — it is peace after effort.',
    topics: 'tawakkul, trust, anxiety', keywords: 'reliance, trust, anxiety, means', ...G,
  },
  {
    slug: 'glossary-laylat-qadr', title: 'Laylat al-Qadr', category: 'time',
    arabicText: 'لَيْلَةُ الْقَدْرِ',
    englishText: 'The Night of Decree — the night the Qur\'an was first sent down, "better than a thousand months" (97:3). Hidden in the odd nights of the last ten of Ramadan.',
    explanation: '"Whoever stands in prayer on it with faith and seeking reward, his previous sins are forgiven" (Bukhari 1901). The recommended dua: "Allahumma innaka \'Afuwwun tuhibbul-\'afwa fa\'fu \'anni."',
    topics: 'ramadan, laylat qadr, time', keywords: 'night of power, qadr, night of decree', ...G,
  },
  {
    slug: 'glossary-hajj', title: 'Hajj', category: 'worship',
    arabicText: 'الحَجّ',
    englishText: 'The pilgrimage to Makkah once in a lifetime (for those able) — the fifth pillar, reenacting the rites of Ibrahim, Hajar, and the Prophet ﷺ, uniting millions in identical white garments.',
    explanation: '"And proclaim the Pilgrimage among mankind: they will come to you on foot… " (22:27). Occurs in Dhul-Hijjah; Eid al-Adha and the Day of Arafah anchor its days.',
    topics: 'hajj, pilgrimage, pillars', keywords: 'pilgrimage, makkah, dhul hijjah, umrah', ...G,
  },
  {
    slug: 'glossary-halal-haram', title: 'Halal / Haram', category: 'fiqh',
    arabicText: 'الحَلَال / الحَرَام',
    englishText: 'Halal: permitted by Allah. Haram: forbidden. Between them are gray areas a careful believer avoids (per the sound narration "whoever falls into the doubtful falls into the haram").',
    explanation: 'The default in Islam is permissibility until a clear text states otherwise — and every haram has a halal alternative Allah provides (a principle from the sound narrations).',
    topics: 'halal, haram, fiqh', keywords: 'permitted, forbidden, lawful, unlawful', ...G,
  },
];
