import type { SeedRecord } from './shared';

// ============================================================================
// HADITH — curated verified records.
// Core source: Sahih al-Bukhari; supplemented by Sahih Muslim, Jami'
// at-Tirmidhi, Sunan Abi Dawud, Sunan an-Nasa'i, Ibn Majah.
// Numbering follows the widely-used English edition numbering
// (Darussalam / sunnah.com) and may differ in other editions — this is stated
// on every citation card. Where BASIRA could not confirm a number with
// confidence, hadithNumber is NULL and the record shows
// "reference pending verification" — this is a feature of the
// no-hallucination policy, not an error.
// Translations are BASIRA's careful simple-English renderings (public domain).
// Arabic text is included only where the wording is confidently known;
// otherwise it is left empty rather than guessed.
// ============================================================================

const H = { sourceType: 'HADITH', verificationStatus: 'VERIFIED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15' } as const;
const P = { sourceType: 'HADITH', verificationStatus: 'REFERENCE_PENDING', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15' } as const;
const D = { sourceType: 'HADITH', verificationStatus: 'DISPUTED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15' } as const;
const BK = 'Sahih al-Bukhari';
const MU = 'Sahih Muslim';
const TM = "Jami' at-Tirmidhi";
const AD = 'Sunan Abi Dawud';
const NS = "Sunan an-Nasa'i";

export const HADITH_SEED: SeedRecord[] = [
  // ————— Foundations: Bukhari's opening —————
  {
    slug: 'hadith-bukhari-1', title: 'Actions are but by intentions',
    collection: BK, book: 'Book of Revelation (opening hadith of the Sahih)', hadithNumber: 1, narrator: 'Umar ibn al-Khattab',
    arabicText: 'سَمِعْتُ رَسُولَ اللَّهِ ﷺ يَقُولُ: «إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ فَهِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ، وَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا أَوِ امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ»',
    englishText: 'I heard the Messenger of Allah ﷺ say: "Actions are only by intentions, and every person shall have only what he intended. Whoever\'s migration was for Allah and His Messenger, his migration was for Allah and His Messenger; whoever\'s migration was for worldly gain or a woman to marry, his migration was for whatever he migrated for."',
    explanation: 'The first hadith of Sahih al-Bukhari and one of the pillars of Islamic law (some scholars called it a third of Islam). The value of any deed — prayer, charity, study, work — depends on the sincerity and direction of the intention behind it.',
    topics: 'intentions, sincerity, actions, faith', keywords: 'niyyah, niyyat, intention, sincerity, migrate', ...H,
  },
  {
    slug: 'hadith-bukhari-8', title: 'Islam is built upon five',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 8, narrator: 'Abdullah ibn Umar',
    arabicText: '«بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلاَةِ، وَإِيتَاءِ الزَّكَاةِ، وَالْحَجِّ، وَصَوْمِ رَمَضَانَ»',
    englishText: 'Islam is built upon five: the testimony that there is no god but Allah and that Muhammad is the Messenger of Allah; establishing prayer; giving zakat; the pilgrimage to the House; and fasting the month of Ramadan.',
    explanation: 'The famous "five pillars" hadith. It summarizes the essential practices of Islam — the structure every beginner course starts with.',
    topics: 'pillars, faith, islam, prayer, zakat, hajj, fasting, shahadah', keywords: 'five pillars, arkan, basics, beginner', ...H,
  },
  {
    slug: 'hadith-bukhari-13', title: 'None of you believes until he loves for his brother',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 13, narrator: 'Anas ibn Malik',
    arabicText: '«لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ»',
    englishText: 'None of you truly believes until he loves for his brother what he loves for himself.',
    explanation: 'Faith is incomplete without sincere goodwill toward others — wishing people the same goodness you wish for yourself, free of envy.',
    topics: 'faith, kindness, manners, brotherhood, love', keywords: 'brother, love, believe, envy', ...H,
  },
  {
    slug: 'hadith-bukhari-religion-easy', title: 'The religion is easy',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: null,
    referenceNote: 'Reported in the Book of Belief; commonly numbered 9 or 39 depending on the edition, so BASIRA shows no single number.',
    narrator: 'Aisha',
    arabicText: '«إِنَّ الدِّينَ يُسْرٌ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلاَّ غَلَبَهُ، فَسَدِّدُوا وَقَارِبُوا وَأَبْشِرُوا، وَاسْتَعِينُوا بِالْغَدْوَةِ وَالرَّوْحِ وَشَيْءٍ مِنَ الدُّلْجَةِ»',
    englishText: 'The religion is ease; no one makes it harsh upon himself except that it overwhelms him. So aim for what is right and draw near, receive good tidings, and seek help in the morning, the evening, and part of the late night.',
    explanation: 'A mercy-principle of Islam: consistency over intensity. "Saddidu wa qaribu" — be balanced and steady rather than extreme. Especially healing for Muslims who feel their worship must be perfect to count.',
    topics: 'ease, balance, worship, anxiety, gentleness', keywords: 'easy, extremism, consistency, moderation', ...P,
  },
  {
    slug: 'hadith-bukhari-38', title: 'Whoever fasts Ramadan with faith',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 38, narrator: 'Abu Huraira',
    arabicText: '«مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»',
    englishText: 'Whoever fasts Ramadan out of sincere faith and seeking Allah\'s reward, his previous sins will be forgiven.',
    explanation: 'Fasting with iman (faith) and ihtisab (hoping only for Allah\'s reward) wipes the slate of past sins — the same wording used for the rewards of standing in prayer on Laylat al-Qadr.',
    topics: 'ramadan, fasting, forgiveness', keywords: 'fast, ramadhan, sins forgiven', ...H,
  },
  {
    slug: 'hadith-bukhari-50', title: 'The Hadith of Jibril',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 50, narrator: 'Abu Huraira',
    arabicText: 'قَالَ: «مَا الإِحْسَانُ؟» قَالَ: «أَنْ تَعْبُدَ اللَّهَ كَأَنَّكَ تَرَاهُ، فَإِنْ لَمْ تَكُنْ تَرَاهُ فَإِنَّهُ يَرَاكَ»',
    englishText: 'While we were sitting with the Prophet ﷺ, a man in very white clothes and very black hair appeared before us, with no trace of travel, and none of us knew him. He sat facing the Prophet, knees to knees, hands on thighs, and asked: "Muhammad, tell me about Islam." He replied: "Islam is to testify there is no god but Allah and that Muhammad is the Messenger of Allah, to establish prayer, give zakat, fast Ramadan, and make pilgrimage to the House if you are able." He said: "You have spoken truthfully." … He asked: "Tell me about Iman (faith)." He replied: "To believe in Allah, His angels, His books, His messengers, the Last Day, and to believe in the divine decree — its good and its hardship." … He asked: "Tell me about Ihsan (excellence)." He replied: "To worship Allah as though you see Him; for if you do not see Him, He surely sees you." … He asked: "Tell me about the Hour." He replied: "The one being asked knows no more about it than the asker." … Then the Prophet ﷺ said: "That was Jibril; he came to teach you your religion."',
    explanation: 'The "Hadith of Jibril" — the complete map of the religion in one scene: Islam (practice), Iman (belief), Ihsan (excellence), and the unseen Hour. The strange visitor was the angel Jibril in human form. The Arabic above is the segment on ihsan; the full report is at the reference.',
    topics: 'faith, islam, ihsan, jibril, knowledge, pillars, aqeedah, decree', keywords: 'jibril, gabriel, islam iman ihsan, angel, hour, hadith of gabriel', ...H,
  },
  {
    slug: 'hadith-bukhari-71', title: 'Whoever Allah wants good for',
    collection: BK, book: 'Book of Knowledge (Kitab al-Ilm)', hadithNumber: 71, narrator: 'Muawiya ibn Abi Sufyan',
    arabicText: '«مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ»',
    englishText: 'When Allah wants good for a person, He grants him understanding of the religion.',
    explanation: 'Religious understanding (fiqh) is itself a gift and sign of divine care. It motivates study — but also humility: comprehension comes from Allah\'s bounty.',
    topics: 'knowledge, learning, faith', keywords: 'understanding, fiqh, teaching, scholar', ...H,
  },
  {
    slug: 'hadith-bukhari-110', title: 'Whoever lies about me deliberately',
    collection: BK, book: 'Book of Knowledge (Kitab al-Ilm)', hadithNumber: 110, narrator: 'Al-Mughira ibn Shu\'ba',
    arabicText: '«مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ»',
    englishText: 'Whoever tells a lie against me deliberately, let him take his seat in the Fire.',
    explanation: 'The strongest warning in the hadith corpus. This is why BASIRA never invents hadith or attributions, and why Muslim scholars built the entire isnad (chain) science — to protect the Prophet\'s ﷺ words from fabrication. If BASIRA cannot verify a report, it says so.',
    topics: 'lying, hadith, fabrication, truthfulness', keywords: 'false attribution, lie, fabricate, isnad', ...H,
  },
  {
    slug: 'hadith-bukhari-3', title: 'How the revelation began',
    collection: BK, book: 'Book of Revelation (Kitab Bad\' al-Wahy)', hadithNumber: 3, narrator: 'Aisha',
    englishText: 'The first form of revelation to the Messenger of Allah ﷺ was true visions in sleep: whatever he saw in a dream came to pass like the breaking of morning light. Then seclusion became beloved to him, and he would retreat in the cave of Hira, worshipping there for many nights before returning to Khadijah. Then truth came to him while he was in the cave: the angel came and said, "Read!" He said, "I am not able to read." The Prophet ﷺ said: "So he took hold of me and pressed me until I could bear it no more, then released me and said: \'Read!\' I said: \'I am not able to read.\' … Then he released me and said: \'Read, in the name of your Lord who created — created man from a clinging form.\'" The Messenger of Allah ﷺ returned trembling and said: "Wrap me up!" … Thereafter revelation paused for a while, until he became saddened, then the revelation returned with "O you wrapped in your cloak — arise and warn."',
    explanation: 'Aisha\'s detailed account of the first revelation (this is Hadith 3; the full text is among the longest in Bukhari — abridged here). It marks the start of prophethood at age forty and connects with Surah al-\'Alaq 96:1-5.',
    topics: 'revelation, seerah, knowledge, first revelation, prophet', keywords: 'cave hira, iqra, jibril, wahy, began', ...H,
  },

  // ————— Salah —————
  {
    slug: 'hadith-bukhari-631', title: 'Pray as you have seen me praying',
    collection: BK, hadithNumber: 631, narrator: 'Malik ibn Huwairith',
    arabicText: '«ارْجِعْ إِلَى أَهْلِكَ فَعَلِّمْهُمْ… وَصَلِّ كَمَا رَأَيْتُمُونِي أُصَلِّي»',
    englishText: 'The Prophet ﷺ said to a group of young companions: "Return to your families and teach them…" and he instructed them to "pray as you have seen me praying."',
    explanation: 'The divine instruction for HOW we learn prayer: by transmitted example, not invention. Every detail of the prayer — standing, bowing, prostrating — traces back to the Prophet\'s ﷺ demonstrated practice.',
    topics: 'prayer, salah, learning', keywords: 'pray, teach, how to pray, example', ...H,
  },
  {
    slug: 'hadith-abudawud-61', title: 'The key of prayer is purity',
    collection: AD, book: 'Book of Purification', hadithNumber: 61, narrator: 'Ali ibn Abi Talib', grade: 'Sahih (authenticated)',
    arabicText: '«مِفْتَاحُ الصَّلاَةِ الطُّهُورُ، وَتَحْرِيمُهَا التَّكْبِيرُ، وَتَحْلِيلُهَا التَّسْلِيمُ»',
    englishText: 'The key of prayer is purification (taharah); its opening is the takbir (saying "Allah is greater"), and its release is the taslim (the closing salam).',
    explanation: 'A concise fiqh map of the prayer\'s frame: no prayer without wudu; it formally begins with takbirat al-ihram and ends with the salam.',
    topics: 'prayer, salah, wudu, purity', keywords: 'key, takbir, taslim, purification', ...H,
  },
  {
    slug: 'hadith-bukhari-164', title: 'Uthman\'s demonstration of wudu',
    collection: BK, book: 'Book of Ablution (Kitab al-Wudu)', hadithNumber: 164, narrator: 'Uthman ibn Affan',
    arabicText: '«…فَغَسَلَ كَفَّيْهِ ثَلاَثَ مَرَّاتٍ، ثُمَّ مَضْمَضَ وَاسْتَنْثَرَ ثَلاَثَ مَرَّاتٍ، ثُمَّ غَسَلَ وَجْهَهُ ثَلاَثَ مَرَّاتٍ، ثُمَّ غَسَلَ يَدَهُ الْيُمْنَى إِلَى الْمَرْفِقِ ثَلاَثَ مَرَّاتٍ، ثُمَّ الْيُسْرَى مِثْلَ ذَلِكَ، ثُمَّ مَسَحَ رَأْسَهُ، ثُمَّ غَسَلَ رِجْلَهُ الْيُمْنَى إِلَى الْكَعْبَيْنِ ثَلاَثَ مَرَّاتٍ، ثُمَّ الْيُسْرَى مِثْلَ ذَلِكَ…»',
    englishText: 'Uthman ibn Affan called for water for wudu. He washed his hands three times, then rinsed his mouth and nose three times, then washed his face three times, then washed his right arm to the elbow three times, then the left likewise, then wiped his head, then washed his right foot to the ankle three times, then the left likewise, then raised his gaze and said: "I saw the Messenger of Allah ﷺ perform wudu like this wudu of mine."',
    explanation: 'The companions transmitted the Prophet\'s ﷺ wudu by careful demonstration. Related narrations in Sahih Muslim (commonly cited as nos. 226 and 244-246) add: "Whoever performs wudu like this, his previous sins are forgiven."',
    topics: 'wudu, purity, prayer, salah', keywords: 'ablution, wash, three times, demonstrate', ...H,
  },
  {
    slug: 'hadith-bukhari-528', title: 'The five prayers wipe away sins',
    collection: BK, book: 'Book of the Times of the Prayers', hadithNumber: 528, narrator: 'Abu Huraira',
    arabicText: '«الصَّلَوَاتُ الْخَمْسُ، وَالْجُمُعَةُ إِلَى الْجُمُعَةِ، وَرَمَضَانُ إِلَى رَمَضَانَ، مُكَفِّرَاتٌ مَا بَيْنَهُنَّ إِذَا اجْتُنِبَ الْكَبَائِرُ»',
    englishText: 'The five daily prayers, Friday to Friday, and Ramadan to Ramadan are expiations for what is between them — as long as the major sins are avoided.',
    explanation: 'Regular prayer is a spiritual washing machine: it cleanses the small sins accumulated between prayers. Major sins need specific repentance (tawbah).',
    topics: 'prayer, salah, forgiveness, jumuah, ramadan', keywords: 'expiation, sins, five prayers, expiate', ...H,
  },
  {
    slug: 'hadith-bukhari-597', title: 'Whoever forgets a prayer',
    collection: BK, book: 'Book of the Times of the Prayers', hadithNumber: 597, narrator: 'Anas ibn Malik',
    arabicText: '«مَنْ نَسِيَ صَلاَةً فَلْيُصَلِّ إِذَا ذَكَرَهَا، وَلاَ كَفَّارَةَ لَهَا إِلاَّ ذَلِكَ»',
    englishText: 'Whoever forgets a prayer should pray it as soon as he remembers it; there is no expiation for it except that.',
    explanation: 'Mercy, not guilt: a forgotten prayer is simply made up when remembered — prayed promptly, in order if the next prayer time hasn\'t yet entered (details differ between schools). No "penalty ritual" exists in Islam for forgetting.',
    topics: 'prayer, salah, missed prayer, forgetfulness', keywords: 'forgot prayer, missed salah, make up, qada', ...H,
  },
  {
    slug: 'hadith-bukhari-asr-warning', title: 'Whoever abandons the Asr prayer',
    collection: BK, hadithNumber: null,
    referenceNote: 'Reported in Sahih al-Bukhari; commonly numbered 553 or 580 depending on the edition, so BASIRA shows no single number.',
    narrator: 'Buraida ibn al-Husaib',
    arabicText: '«مَنْ تَرَكَ صَلاَةَ الْعَصْرِ فَقَدْ حَبِطَ عَمَلُهُ»',
    englishText: 'Whoever abandons the Asr prayer, his deeds are rendered void.',
    explanation: 'Scholars explain this severe wording refers to deliberately abandoning prayer while denying its obligation — not to a believer who oversleeps or forgets (see the previous hadith on making up missed prayers). The warning shows Asr\'s seriousness: the middle prayer, hardest to leave work for.',
    topics: 'prayer, salah, asr, warning', keywords: 'asr, afternoon, abandon, void', ...P,
  },
  {
    slug: 'hadith-bukhari-659', title: 'The heaviest prayers for the hypocrites',
    collection: BK, hadithNumber: 659, narrator: 'Abu Huraira',
    arabicText: '«لَيْسَ صَلاَةٌ أَثْقَلَ عَلَى الْمُنَافِقِينَ مِنْ صَلاَةِ الْفَجْرِ وَصَلاَةِ الْعِشَاءِ، وَلَوْ يَعْلَمُونَ مَا فِيهِمَا لَأَتَوْهُمَا وَلَوْ حَبْوًا»',
    englishText: 'No prayer is heavier upon the hypocrites than the Fajr and Isha prayers; yet if they knew what reward is in them, they would come even if they had to crawl.',
    explanation: 'Fajr and Isha test sincerity — prayed in private hours when nobody sees. Their reward is described as beyond what most imagine. Encouragement for the struggling believer: Allah knows the effort even when no one else does.',
    topics: 'prayer, salah, fajr, isha, sincerity', keywords: 'dawn, night prayer, hypocrites, fajr, isha', ...H,
  },
  {
    slug: 'hadith-muslim-725', title: 'The two rakʿahs of Fajr',
    collection: MU, book: 'Book of Prayer', hadithNumber: 725, narrator: 'Aisha',
    arabicText: '«رَكْعَتَا الْفَجْرِ خَيْرٌ مِنَ الدُّنْيَا وَمَا فِيهَا»',
    englishText: 'The two rakʿahs of Fajr (the sunnah before it) are better than the world and everything in it.',
    explanation: 'A short sunnah prayer of a few minutes outweighs the entire universe — Allah\'s scales are not ours. The Prophet ﷺ never left these two light rakʿahs, even while traveling.',
    topics: 'prayer, salah, fajr, sunnah', keywords: 'two rakahs, fajr sunnah, dawn', ...H,
  },
  {
    slug: 'hadith-muslim-657', title: 'Whoever prays the two cool prayers enters Paradise',
    collection: MU, book: 'Book of Prayer', hadithNumber: 657, narrator: 'Abu Musa al-Ash\'ari',
    arabicText: '«مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ»',
    englishText: 'Whoever prays the two cool prayers will enter Paradise.',
    explanation: 'The "two cool prayers" (al-bardatan) are Fajr and Asr — the prayers at the two cool ends of the day. Consistency in them is a signature of true faith.',
    topics: 'prayer, salah, fajr, asr, jannah', keywords: 'cool prayers, fajr, asr, paradise', ...H,
  },
  {
    slug: 'hadith-bukhari-844', title: 'Dhikr after the prayer',
    collection: BK, book: 'Book of the Call to Prayer (Adhan)', hadithNumber: 844, narrator: 'Al-Mughira ibn Shu\'ba',
    arabicText: '«لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ»',
    englishText: 'After the taslim, the Prophet ﷺ would say: "There is no god but Allah alone, with no partner; to Him belongs the kingdom and all praise, and He is able to do all things. O Allah, none can withhold what You give, none can give what You withhold, and the fortune of the fortunate means nothing with You."',
    explanation: 'The Prophetic dhikr immediately after finishing the prayer — affirming that all provision and withholding belong to Allah alone.',
    topics: 'prayer, salah, dhikr, after prayer', keywords: 'after salah, post prayer dhikr, tasbih', ...H,
  },
  {
    slug: 'hadith-muslim-591', title: 'Seeking forgiveness after prayer',
    collection: MU, book: 'Book of Prayer', hadithNumber: 591,
    arabicText: '«أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ. اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ»',
    englishText: 'When the Messenger of Allah ﷺ finished his prayer he would seek Allah\'s forgiveness three times and say: "O Allah, You are Peace and from You comes peace; blessed are You, O Owner of Majesty and Honor."',
    explanation: 'The first words after taslim: istighfar x3, then the beautiful name-dua. A gentle transition from the audience with Allah back into the world.',
    topics: 'prayer, salah, forgiveness, dhikr, after prayer', keywords: 'astaghfirullah, after salah, peace', ...H,
  },
  {
    slug: 'hadith-muslim-597', title: 'Glorify Allah thirty-three times after prayer',
    collection: MU, book: 'Book of Prayer', hadithNumber: 597, narrator: 'Abu Huraira',
    arabicText: '«مَنْ سَبَّحَ اللَّهَ فِي دُبُرِ كُلِّ صَلاَةٍ ثَلاَثًا وَثَلاَثِينَ، وَحَمِدَ اللَّهَ ثَلاَثًا وَثَلاَثِينَ، وَكَبَّرَ اللَّهَ ثَلاَثًا وَثَلاَثِينَ، فَتِلْكَ تِسْعَةٌ وَتِسْعُونَ، وَقَالَ تَمَامَ الْمِائَةِ: لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، غُفِرَتْ خَطَايَاهُ وَإِنْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ»',
    englishText: 'Whoever glorifies Allah after every prayer thirty-three times (SubhanAllah), praises Allah thirty-three times (Alhamdulillah), magnifies Allah thirty-three times (Allahu Akbar) — making ninety-nine — and then completes one hundred by saying: "There is no god but Allah alone, with no partner; to Him belongs the kingdom and all praise, and He is able to do all things" — his sins are forgiven, even if they are like the foam of the sea.',
    explanation: 'The famous 33-33-33-1 dhikr. About 90 seconds after each prayer with the promise of ocean-sized forgiveness. The numbers come from the source — BASIRA displays them exactly as narrated.',
    topics: 'dhikr, prayer, salah, after prayer, forgiveness', keywords: '33, tasbih, subhanallah, alhamdulillah, allahu akbar, hundred', targetCount: 33, ...H,
  },
  {
    slug: 'hadith-bukhari-tarawih', title: 'Praying at night in Ramadan',
    collection: BK, book: 'Book of Praying at Night in Ramadan (Tahajjud)', hadithNumber: null,
    referenceNote: 'Reported in Sahih al-Bukhari; commonly numbered near 1129, so BASIRA shows no single number.',
    narrator: 'Aisha',
    englishText: 'The Prophet ﷺ went out in the middle of one night in Ramadan and prayed in the mosque, and some people prayed behind him. The next night people gathered again and more prayed; then on the third or fourth night the people gathered, but the Messenger of Allah ﷺ did not come out. When morning came he said: "I saw what you were doing, and nothing prevented me from coming out except that I feared it would be made obligatory upon you."',
    explanation: 'The origin of Tarawih as congregation. The Prophet ﷺ stopped it publicly out of mercy — fearing a binding obligation — and it was Umar ibn al-Khattab who later established the communal Tarawih, which Muslims continue today.',
    topics: 'ramadan, tarawih, prayer, night prayer', keywords: 'taraweeh, night, ramadan, congregation', ...P,
  },
  {
    slug: 'hadith-abudawud-1416', title: 'Allah has given you an extra prayer: Witr',
    collection: AD, book: 'Book of Witr', hadithNumber: 1416, grade: 'Sahih (authenticated)',
    englishText: 'Allah has given you an additional prayer beyond the five: it is al-Witr. Pray it between the Isha prayer and the dawn prayer.',
    explanation: 'Witr ("odd-numbered") is a recommended night prayer — the Prophet ﷺ never left it, at home or traveling. Schools differ on details (whether it is one, three, or more rakʿahs, and its precise manner) — see BASIRA\'s Fiqh section for the positions.',
    topics: 'witr, prayer, salah, night prayer', keywords: 'witr, odd, night prayer, isha', ...H,
  },
  {
    slug: 'hadith-bukhari-friday-rituals', title: 'The Friday bath and etiquette',
    collection: BK, book: 'Book of Friday (Kitab al-Jumu\'ah)', hadithNumber: null,
    referenceNote: 'Reported in the Book of Friday; commonly cited near hadith 883, so BASIRA shows no single number.',
    narrator: 'Abu Huraira',
    englishText: 'Whoever takes a bath on Friday, purifies himself as much as he can, applies oil or perfume, then goes out to the mosque without stepping between two people, then prays what is appointed for him, then keeps silent when the imam speaks — Allah will forgive what is between that Friday and the next.',
    explanation: 'The Prophetic sunnahs of Jumu\'ah in a single hadith: ghusl, cleanliness, fragrance, walking (not driving recklessly!), avoiding stepping over people, praying the sunnahs, and — most emphasized — listening attentively to the khutbah.',
    practicalSteps: [
      'Perform ghusl (full bath) before going.',
      'Wear your best clean clothes and apply a pleasant scent.',
      'Go early — "the earlier, the greater the reward" (as other narrations describe camels, cows, rams being offered in imagery).',
      'Pray the mosque\'s greeting (tahiyyat al-masjid) and extra voluntary prayers.',
      'Listen silently and attentively to the khutbah.',
      'Send abundant blessings (salawat) upon the Prophet ﷺ during the day, and recite Surah al-Kahf (see note on its grading).',
    ],
    topics: 'jumuah, friday, prayer, salah, sunnah', keywords: 'friday, jumuah, bath, ghusl, khutbah, sermon', ...P,
  },
  {
    slug: 'hadith-kahf-friday', title: 'Reciting Surah al-Kahf on Friday',
    collection: 'Reported by an-Nasa\'i and al-Bayhaqi (outside the six core collections)', hadithNumber: null,
    referenceNote: 'This report is not in the six main collections. Some scholars (e.g., al-Albani) graded the raised (marfuʿ) version good/authentic; others considered its chain weak while authenticating the companion-version. BASIRA labels it accordingly rather than presenting it as agreed.',
    verificationStatus: 'DISPUTED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15', sourceType: 'HADITH',
    englishText: 'Whoever recites Surah al-Kahf on Friday, a light will shine for him from one Friday to the next.',
    explanation: 'A widely beloved practice. Because its authentication is debated, BASIRA presents it as DISPUTED: scholars who grade it authentic encourage the recitation; those who consider it weak view the recitation of Surah al-Kahf as rewarding in its own right at any time. Either way, reciting Qur\'an on Friday is praiseworthy.',
    topics: 'jumuah, friday, quran, kahf, dhikr', keywords: 'cave surah, friday, recite, light', ...D,
  },
  {
    slug: 'hadith-ayat-kursi-after-prayer', title: 'Ayat al-Kursi after each prayer',
    collection: 'Reported by an-Nasa\'i (\'Amal al-Yawm wal-Laylah) and at-Tabarani', hadithNumber: null,
    referenceNote: 'Not found in the six main collections. Graded authentic by some scholars (e.g., al-Albani in Sahih al-Jamiʿ); others note weakness in some chains. BASIRA labels it accordingly.',
    verificationStatus: 'DISPUTED', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15', sourceType: 'HADITH',
    englishText: 'Whoever recites Ayat al-Kursi (Qur\'an 2:255) after every obligatory prayer, nothing stands between him and entering Paradise except death.',
    explanation: 'Ayat al-Kursi\'s recitation after prayers is a cherished practice based on this report. Given its debated authentication, BASIRA shows it as DISPUTED — the believer may practice it with the intention of following the narration, while knowing its grade is discussed by scholars.',
    topics: 'prayer, salah, dhikr, protection, quran', keywords: 'ayat al-kursi, throne verse, after prayer', ...D,
  },

  // ————— Ramadan & fasting —————
  {
    slug: 'hadith-muslim-1079', title: 'When Ramadan begins',
    collection: MU, book: 'Book of Fasting (Kitab as-Siyam)', hadithNumber: 1079, narrator: 'Abu Huraira',
    arabicText: '«إِذَا جَاءَ رَمَضَانُ فُتِّحَتْ أَبْوَابُ الْجَنَّةِ، وَغُلِّقَتْ أَبْوَابُ النَّارِ، وَصُفِّدَتِ الشَّيَاطِينُ»',
    englishText: 'When Ramadan arrives, the gates of Paradise are opened, the gates of the Fire are locked, and the devils are chained.',
    explanation: 'Also reported in Sahih al-Bukhari with the wording "the gates of the heavens are opened" and "the gates of mercy are opened" — the narrations complement one another. Ramadan is a protected season of unusual spiritual openness.',
    topics: 'ramadan, fasting, mercy, jannah', keywords: 'gates, paradise, devils chained, ramadhan', ...H,
  },
  {
    slug: 'hadith-bukhari-2017', title: 'Seek Laylat al-Qadr in the odd nights',
    collection: BK, book: 'Book of Praying at Night (Tahajjud)', hadithNumber: 2017,
    arabicText: '«تَحَرَّوْا لَيْلَةَ الْقَدْرِ فِي الْوِتْرِ مِنَ الْعَشْرِ الأَوَاخِرِ مِنْ رَمَضَانَ»',
    englishText: 'Seek Laylat al-Qadr in the odd nights of the last ten nights of Ramadan.',
    explanation: 'The Night of Decree is hidden precisely so that believers seek it with effort — every odd night of the last ten becomes an appointment: 21st, 23rd, 25th, 27th, 29th.',
    topics: 'ramadan, laylat qadr, night of power', keywords: 'odd nights, last ten, qadr, seek', ...H,
  },
  {
    slug: 'hadith-bukhari-1901', title: 'Standing in prayer on Laylat al-Qadr',
    collection: BK, book: 'Book of Fasting', hadithNumber: 1901, narrator: 'Abu Huraira',
    arabicText: '«مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»',
    englishText: 'Whoever stands in prayer on the Night of Qadr out of faith and seeking reward, his previous sins will be forgiven.',
    explanation: 'A few hours of night worship on one night can erase a lifetime of past sins — "better than a thousand months" (Qur\'an 97:3).',
    topics: 'ramadan, laylat qadr, prayer, forgiveness', keywords: 'stand, night of power, forgiven', ...H,
  },
  {
    slug: 'hadith-tirmidhi-807', title: 'Whoever feeds a fasting person',
    collection: TM, book: 'Book of Fasting', hadithNumber: 807, grade: 'Hasan Sahih (sound)',
    arabicText: '«مَنْ فَطَّرَ صَائِمًا كَانَ لَهُ مِثْلُ أَجْرِهِ، غَيْرَ أَنَّهُ لاَ يَنْقُصُ مِنْ أَجْرِ الصَّائِمِ شَيْئًا»',
    englishText: 'Whoever provides iftar for a fasting person receives a reward like his, without the fasting person\'s reward being reduced at all.',
    explanation: 'The iftar-table charity: hosting fasting people — family, community, the poor — multiplies reward without diminishing anyone\'s share.',
    topics: 'ramadan, fasting, charity, kindness', keywords: 'feed, iftar, fasting person, reward', ...H,
  },

  // ————— Character & manners —————
  {
    slug: 'hadith-muslim-40', title: 'The Muslim is the one people are safe from',
    collection: MU, book: 'Book of Faith (Kitab al-Iman)', hadithNumber: 40, narrator: 'Abu Huraira',
    arabicText: '«الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ»',
    englishText: 'The Muslim is the one from whose tongue and hand the Muslims are safe.',
    explanation: 'The Qur\'anic definition of a believer in society: others must be safe from your words and your actions — online, at work, at home. (The full hadith adds: "and the emigrant is the one who abandons what Allah has forbidden.")',
    topics: 'manners, kindness, speech, character', keywords: 'tongue, hand, safe, harm, muslim', ...H,
  },
  {
    slug: 'hadith-bukhari-33', title: 'The signs of the hypocrite',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 33, narrator: 'Abu Huraira',
    arabicText: '«آيَةُ الْمُنَافِقِ ثَلاَثٌ: إِذَا حَدَّثَ كَذَبَ، وَإِذَا وَعَدَ أَخْلَفَ، وَإِذَا اؤْتُمِنَ خَانَ»',
    englishText: 'The signs of a hypocrite are three: when he speaks, he lies; when he promises, he breaks it; and when he is entrusted, he betrays the trust.',
    explanation: 'A warning-mirror, not a license to judge others: the believer checks these three against their own self first. Lying, promise-breaking, and treachery are the anatomy of hypocrisy.',
    topics: 'lying, truthfulness, manners, trust', keywords: 'hypocrite, nifaq, lie, promise, trust', ...H,
  },
  {
    slug: 'hadith-bukhari-6094', title: 'Truthfulness leads to righteousness',
    collection: BK, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: 6094, narrator: 'Abdullah ibn Mas\'ud',
    arabicText: '«إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ، وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ، وَإِنَّ الرَّجُلَ لَيَصْدُقُ حَتَّى يَكُونَ صِدِّيقًا، وَإِنَّ الْكَذِبَ يَهْدِي إِلَى الْفُجُورِ، وَإِنَّ الْفُجُورَ يَهْدِي إِلَى النَّارِ، وَإِنَّ الرَّجُلَ لَيَكْذِبُ حَتَّى يُكْتَبَ عِنْدَ اللَّهِ كَذَّابًا»',
    englishText: 'Truthfulness leads to righteousness, and righteousness leads to Paradise; a man keeps speaking truth until he is written with Allah as utterly truthful (siddiq). Lying leads to wickedness, and wickedness leads to the Fire; a man keeps lying until he is written with Allah as a liar.',
    explanation: 'Character is a trajectory: every truthful word makes the next easier, every lie does the same for its opposite. Islam treats honesty as trainable muscle, not fixed nature.',
    topics: 'lying, truthfulness, manners, character', keywords: 'truth, lie, siddiq, honesty', ...H,
  },
  {
    slug: 'hadith-bukhari-6018', title: 'Honor your neighbor, your guest — and speak good',
    collection: BK, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: null,
    referenceNote: 'Reported in the Book of Manners; commonly cited near hadith 6018 in the standard numbering, so BASIRA shows no single number.',
    narrator: 'Abu Huraira',
    arabicText: '«مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلاَ يُؤْذِ جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ»',
    englishText: 'Whoever believes in Allah and the Last Day, let him not harm his neighbor. Whoever believes in Allah and the Last Day, let him honor his guest. Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    explanation: 'Three social commandments tied directly to faith. The last phrase — "speak good or be silent" — is the Islamic discipline of the tongue in six words.',
    topics: 'neighbors, guests, speech, manners, kindness', keywords: 'neighbor, guest, speak, silent, harm', ...P,
  },
  {
    slug: 'hadith-bukhari-6927', title: 'Allah is gentle and loves gentleness',
    collection: BK, hadithNumber: 6927, narrator: 'Aisha',
    arabicText: '«إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ»',
    englishText: 'Allah is gentle and loves gentleness in all matters.',
    explanation: 'The divine attribute that should shape every human interaction — teaching children, correcting spouses, leading teams, calling to Islam. Related narrations add: "He gives through gentleness what He does not give through violence."',
    topics: 'gentleness, kindness, manners, mercy', keywords: 'gentle, rafiq, rifq, soft', ...H,
  },
  {
    slug: 'hadith-muslim-2592', title: 'Whoever is deprived of gentleness',
    collection: MU, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 2592, narrator: 'Aisha',
    arabicText: '«مَنْ حُرِمَ الرِّفْقَ حُرِمَ الْخَيْرَ كُلَّهُ»',
    englishText: 'Whoever is deprived of gentleness is deprived of all good.',
    explanation: 'Harshness looks strong but harvests nothing. Gentleness is not weakness — it is the container that carries goodness to other hearts.',
    topics: 'gentleness, kindness, manners', keywords: 'gentle, rifq, deprived, good', ...H,
  },
  {
    slug: 'hadith-tirmidhi-1924', title: 'Be merciful to those on earth',
    collection: TM, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 1924, narrator: 'Abdullah ibn Amr', grade: 'Hasan Sahih (sound)',
    arabicText: '«الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ»',
    englishText: 'The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth, and the One in heaven will be merciful to you.',
    explanation: 'Mercity as a law of reciprocity with ar-Rahman Himself. Extends to animals, elders, children, and even the person who wronged you.',
    topics: 'mercy, kindness, manners, compassion', keywords: 'merciful, rahman, earth, heaven', ...H,
  },
  {
    slug: 'hadith-tirmidhi-1956', title: 'Your smile is charity',
    collection: TM, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 1956, narrator: 'Abu Dharr', grade: 'Hasan (sound)',
    arabicText: '«تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَةٌ»',
    englishText: 'Your smile for your brother is charity.',
    explanation: 'The cheapest sadaqah in existence. Islamic kindness is granular: a smile, a good word, removing harm from a path — all count on the scales.',
    topics: 'kindness, manners, charity, smile', keywords: 'smile, charity, sadaqah, face', ...H,
  },
  {
    slug: 'hadith-muslim-2699', title: 'Whoever relieves a believer\'s hardship',
    collection: MU, book: 'Book of Zuhd and Softening the Heart', hadithNumber: 2699, narrator: 'Abu Huraira',
    arabicText: '«مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا، نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ، وَمَنْ يَسَّرَ عَلَى مُعْسِرٍ، يَسَّرَ اللَّهُ عَلَيْهِ فِي الدُّنْيَا وَالآخِرَةِ…»',
    englishText: 'Whoever relieves a believer\'s hardship of this world, Allah will relieve his hardship on the Day of Resurrection. Whoever makes things easy for one in difficulty, Allah will make things easy for him in this world and the next…',
    explanation: 'The hadith continues: "Allah helps the servant as long as the servant helps his brother." The believer\'s daily mission: look for knots to untie in people\'s lives.',
    topics: 'kindness, helping, difficulty, charity, manners', keywords: 'relieve, hardship, ease, help, brother', ...H,
  },
  {
    slug: 'hadith-bukhari-6474', title: 'Guarantee me your tongue and your legs',
    collection: BK, hadithNumber: 6474, narrator: 'Sahl ibn Sa\'d',
    arabicText: '«مَنْ يَضْمَنْ لِي مَا بَيْنَ لَحْيَيْهِ وَرِجْلَيْهِ، أَضْمَنْ لَهُ الْجَنَّةَ»',
    englishText: 'Whoever guarantees for me what is between his jaws and his legs (the tongue and the private parts), I guarantee Paradise for him.',
    explanation: 'Two organs, one promise. Guarding speech and chastity is presented as the fast-track to Paradise — the rest of righteous conduct follows naturally from these.',
    topics: 'speech, chastity, manners, jannah', keywords: 'tongue, jaws, legs, guarantee, paradise', ...H,
  },
  {
    slug: 'hadith-sent-to-perfect-character', title: 'I was sent to perfect good character',
    collection: 'Musnad Ahmad / al-Muwatta (Malik)', hadithNumber: null,
    referenceNote: 'Reported in Musnad Ahmad and al-Muwatta\'; authenticated by some scholars, others discuss its chains. BASIRA shows no number.',
    grade: 'Authenticated by some scholars (graded sahih by al-Albani and others)',
    arabicText: '«إِنَّمَا بُعِثْتُ لِأُتَمِّمَ مَكَارِمَ الأَخْلاَقِ»',
    englishText: 'I was sent only to perfect noble character.',
    explanation: 'The mission statement of the Prophet ﷺ: character completion. ʿAisha described his character as "the Qur\'an" — meaning his life embodied it completely.',
    topics: 'manners, character, seerah, purpose', keywords: 'character, akhlaq, manners, sent, mission', ...P,
  },
  {
    slug: 'hadith-muslim-2564', title: 'Allah does not look at your forms',
    collection: MU, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 2564, narrator: 'Abu Huraira',
    arabicText: '«إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ، وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ»',
    englishText: 'Allah does not look at your forms and your wealth; He looks at your hearts and your deeds.',
    explanation: 'The great equalizer: beauty, fashion, followers, and bank accounts are invisible on Allah\'s scale. The heart\'s state and the deed\'s sincerity are everything.',
    topics: 'sincerity, hearts, deeds, equality', keywords: 'look, form, wealth, hearts, deeds', ...H,
  },

  // ————— Patience, trials, anxiety —————
  {
    slug: 'hadith-bukhari-5641', title: 'Whatever afflicts a Muslim expiates sins',
    collection: BK, book: 'Book of Patients (Kitab al-Marda)', hadithNumber: 5641, narrator: 'Abu Sa\'id al-Khudri and Abu Huraira',
    arabicText: '«مَا يُصِيبُ الْمُسْلِمَ مِنْ هَمٍّ وَلاَ نَصَبٍ وَلاَ وَصَبٍ وَلاَ حَزَنٍ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ سَيِّئَاتِهِ»',
    englishText: 'No worry, exhaustion, pain, or sorrow afflicts a Muslim — even the prick of a thorn — except that Allah expiates some of his sins by it.',
    explanation: 'The divine accounting of suffering: nothing felt is wasted. Anxiety, grief, and physical pain are quietly converting into purification for the believer who endures them with faith.',
    topics: 'patience, trial, anxiety, difficulty, sickness, forgiveness', keywords: 'worry, pain, thorn, expiate, sins', ...H,
  },
  {
    slug: 'hadith-muslim-2999', title: 'Amazing is the affair of the believer',
    collection: MU, book: 'Book of Zuhd', hadithNumber: 2999, narrator: 'Suhayb ibn Sinan',
    arabicText: '«عَجَبًا لأَمْرِ الْمُؤْمِنِ، إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ وَلَيْسَ ذَاكَ لأَحَدٍ إِلاَّ لِلْمُؤْمِنِ: إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ، وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ»',
    englishText: 'Amazing is the affair of the believer: all of it is good — and this is for no one but the believer. If good befalls him he is grateful, and that is good for him; if hardship befalls him he is patient, and that is good for him.',
    explanation: 'The believer holds a supernatural portfolio: profit in every market condition. Gratitude converts ease into reward; patience converts hardship into reward.',
    topics: 'patience, gratitude, trial, faith, anxiety', keywords: 'amazing, believer, patient, grateful, good', ...H,
  },
  {
    slug: 'hadith-bukhari-5999', title: 'Allah is more merciful than this mother',
    collection: BK, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: 5999, narrator: 'Umar ibn al-Khattab',
    arabicText: '«لَلَّهُ أَرْحَمُ بِعِبَادِهِ مِنْ هَذِهِ بِوَلَدِهَا»',
    englishText: 'After the battle, some captives were brought, and a woman searching among them found her child, clutched him to her chest, and nursed him. The Messenger of Allah ﷺ said: "Do you think this woman would throw her child into the fire?" We said: "No, not unless she is unable to hold him." He said: "Allah is more merciful to His servants than this mother is to her child."',
    explanation: 'The Prophet\'s ﷺ most vivid image of divine mercy. Every time you feel your sins disqualify you, remember: the Mercy that runs the universe is stronger than a mother\'s love.',
    topics: 'mercy, forgiveness, hope, repentance', keywords: 'merciful, mother, child, captive, love', ...H,
  },
  {
    slug: 'hadith-muslim-2747', title: 'Allah rejoices at the repentance of His servant',
    collection: MU, book: 'Book of Repentance (Kitab at-Tawbah)', hadithNumber: 2747, narrator: 'Anas ibn Malik',
    englishText: 'Allah is more pleased with the repentance of His servant than a man who camps in a deserted valley and loses his camel carrying his food and drink. He searches until he despairs and says, "I shall return to where I was and sleep until I die." He places his head down to die, then wakes to find his camel standing beside him with its reins — and in extreme joy he says: "O Allah, You are my servant and I am Your lord!" — making a mistake out of the intensity of his joy.',
    explanation: 'The Prophet ﷺ chose an image of life-and-death joy: a man who recovers his survival itself. That is the scale of Allah\'s happiness when you say "Astaghfirullah" and mean it.',
    topics: 'repentance, tawbah, forgiveness, mercy, hope', keywords: 'rejoice, repent, camel, lost, found, joy', ...H,
  },
  {
    slug: 'hadith-bukhari-6307', title: 'I seek Allah\'s forgiveness seventy times a day',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6307, narrator: 'Abu Huraira',
    arabicText: '«وَاللَّهِ إِنِّي لأَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ فِي الْيَوْمِ أَكْثَرَ مِنْ سَبْعِينَ مَرَّةً»',
    englishText: 'By Allah, I seek Allah\'s forgiveness and turn to Him more than seventy times a day.',
    explanation: 'The sinless Prophet ﷺ repented seventy-plus times daily. Istighfar is not a sinner\'s emergency button — it is the believer\'s daily breath, polishing the heart\'s connection.',
    topics: 'repentance, forgiveness, istighfar, dhikr', keywords: 'seventy, seek forgiveness, astaghfirullah, daily', ...H,
  },
  {
    slug: 'hadith-tirmidhi-2499', title: 'Every son of Adam errs',
    collection: TM, book: 'Book of the Description of the Day of Judgement', hadithNumber: 2499, narrator: 'Anas ibn Malik', grade: 'Hasan Sahih (sound)',
    arabicText: '«كُلُّ ابْنِ آدَمَ خَطَّاءٌ، وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ»',
    englishText: 'Every son of Adam errs, and the best of those who err are those who repent.',
    explanation: 'Perfection is not the entry requirement of Islam — return is. The ranking is not "who never fell" but "who got back up".',
    topics: 'repentance, tawbah, forgiveness, sin', keywords: 'err, mistake, sin, repent, adam', ...H,
  },
  {
    slug: 'hadith-ibnmajah-4250', title: 'The one who repents is like the one without sin',
    collection: 'Sunan Ibn Majah', book: 'Book of Zuhd', hadithNumber: 4250, grade: 'Hasan (sound)',
    arabicText: '«التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لاَ ذَنْبَ لَهُ»',
    englishText: 'The one who repents from sin is like the one who has no sin.',
    explanation: 'Tawbah is a reset, not a scar. When repentance is accepted, the past does not trail the believer anymore.',
    topics: 'repentance, tawbah, forgiveness, sin', keywords: 'repent, sin, clean, reset', ...H,
  },

  // ————— Qur\'an & knowledge —————
  {
    slug: 'hadith-bukhari-5027', title: 'The best of you learn the Qur\'an and teach it',
    collection: BK, book: 'Book of the Virtues of the Qur\'an', hadithNumber: 5027, narrator: 'Uthman ibn Affan',
    arabicText: '«خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ»',
    englishText: 'The best of you are those who learn the Qur\'an and teach it.',
    explanation: 'The learned-and-teaching believer sits at the top of the Ummah\'s ranking. Not reciting only — learning its meaning and passing it on.',
    topics: 'quran, knowledge, learning, teaching', keywords: 'best, learn, teach, quran', ...H,
  },
  {
    slug: 'hadith-muslim-810', title: 'The greatest ayah of the Qur\'an',
    collection: MU, book: 'Book of the Prayer of Travelers', hadithNumber: 810, narrator: 'Ubayy ibn Ka\'b',
    englishText: 'The Messenger of Allah ﷺ asked me: "O Abu al-Mundhir, do you know which ayah of Allah\'s Book that is with you is the greatest?" I said: "Allah and His Messenger know best." He said: "It is: \'Allah — there is no god but Him, the Ever-Living, the Sustainer of existence\' (Ayat al-Kursi, 2:255)." He struck my chest and said: "By Allah, Abu al-Mundhir, let this knowledge rejoice your heart!"',
    explanation: 'The Prophet ﷺ personally certified Ayat al-Kursi as the greatest verse of the Qur\'an. See the Dhikr section for its recitations before sleep and (per a debated report) after prayers.',
    topics: 'quran, ayat al-kursi, knowledge', keywords: 'greatest, verse, ayah, ubayy', ...H,
  },
  {
    slug: 'hadith-muslim-49', title: 'Whoever sees an evil, let him change it',
    collection: MU, book: 'Book of Faith (Kitab al-Iman)', hadithNumber: 49, narrator: 'Abu Sa\'id al-Khudri',
    arabicText: '«مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ، وَذَلِكَ أَضْعَفُ الإِيمَانِ»',
    englishText: 'Whoever of you sees an evil, let him change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart — and that is the weakest of faith.',
    explanation: 'The graduated scale of responding to wrong: action within one\'s authority, then truthful speech, then refusal in the heart. Silence of the heart is the one inexcusable level.',
    topics: 'enjoin good, manners, community, justice', keywords: 'evil, munkar, change, forbid, heart', ...H,
  },

  // ————— Dhikr & invocations —————
  {
    slug: 'hadith-bukhari-6405', title: 'SubhanAllahi wa bihamdihi one hundred times',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6405, narrator: 'Abu Huraira',
    arabicText: '«مَنْ قَالَ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ، حُطَّتْ خَطَايَاهُ وَلَوْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ»',
    englishText: 'Whoever says "SubhanAllahi wa bihamdihi" (Glory be to Allah and praise be to Him) one hundred times in a day, his sins are wiped away — even if they were like the foam of the sea.',
    explanation: 'Two minutes, one hundred repetitions, ocean-sized forgiveness. One of the most efficient adhkar ever prescribed.',
    topics: 'dhikr, forgiveness, morning, evening, tasbih', keywords: 'subhanallah, hundred, foam, sea, morning', targetCount: 100, ...H,
  },
  {
    slug: 'hadith-bukhari-6407', title: 'The one who remembers his Lord and the one who does not',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6407, narrator: 'Abu Musa al-Ash\'ari',
    arabicText: '«مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لاَ يَذْكُرُ رَبَّهُ مَثْلُ الْحَيِّ وَالْمَيِّتِ»',
    englishText: 'The example of the one who remembers his Lord and the one who does not is like the living and the dead.',
    explanation: 'Dhikr is not decoration on life — it is life itself. A heart without remembrance is described in the same breath as a body without breath.',
    topics: 'dhikr, remembrance, heart', keywords: 'remember, living, dead, example', ...H,
  },
  {
    slug: 'hadith-bukhari-6682', title: 'Two words light on the tongue, heavy on the scales',
    collection: BK, hadithNumber: 6682, narrator: 'Abu Huraira',
    arabicText: '«كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ»',
    englishText: 'Two words light upon the tongue, heavy upon the scales, beloved to the Most Merciful: "SubhanAllahi wa bihamdih, SubhanAllahil-\'Adheem" (Glory and praise be to Allah; glory be to Allah the Most Great).',
    explanation: 'Weight physics inverted by divine grace: the lightest phrases for the tongue are the heaviest on the scale of deeds.',
    topics: 'dhikr, tasbih, scales, reward', keywords: 'two words, light, heavy, scales, rahman', ...H,
  },
  {
    slug: 'hadith-muslim-408', title: 'Whoever sends one blessing upon me',
    collection: MU, book: 'Book of Prayer', hadithNumber: 408, narrator: 'Abu Huraira',
    arabicText: '«مَنْ صَلَّى عَلَيَّ صَلاَةً وَاحِدَةً صَلَّى اللَّهُ عَلَيْهِ عَشْرَ صَلَوَاتٍ»',
    englishText: 'Whoever sends one blessing upon me, Allah sends ten blessings upon him.',
    explanation: 'Salawat — saying "Allahumma salli \'ala Muhammad" or "Salla Allahu \'alayhi wa sallam" — triggers a tenfold divine response. The single easiest dua with the highest multiplier.',
    topics: 'salawat, dhikr, prophet, dua, friday', keywords: 'blessings, salawat, ten, prophet', ...H,
  },
  {
    slug: 'hadith-bukhari-6306', title: 'Sayyid al-Istighfar — the master of seeking forgiveness',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6306, narrator: 'Shaddad ibn Aws',
    arabicText: '«سَيِّدُ الاِسْتِغْفَارِ أَنْ تَقُولَ: اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ. مَنْ قَالَهَا مِنَ النَّهَارِ مُوقِنًا بِهَا فَمَاتَ مِنْ يَوْمِهِ قَبْلَ أَنْ يُمْسِيَ فَهُوَ مِنْ أَهْلِ الْجَنَّةِ، وَمَنْ قَالَهَا مِنَ اللَّيْلِ وَهُوَ مُوقِنٌ بِهَا فَمَاتَ قَبْلَ أَنْ يُصْبِحَ فَهُوَ مِنْ أَهْلِ الْجَنَّةِ»',
    englishText: 'The master of all seeking of forgiveness is that you say: "O Allah, You are my Lord; there is no god but You. You created me and I am Your servant; I keep Your covenant and promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin — so forgive me, for none forgives sins except You." Whoever says this during the day with certainty and dies before evening, he is of the people of Paradise; and whoever says it at night with certainty and dies before morning, he is of the people of Paradise.',
    explanation: 'The Prophet ﷺ titled this "the master of istighfar" — it fuses tawhid, servanthood, covenant, refuge, gratitude, and confession into one comprehensive dua. Morning and evening.',
    topics: 'dua, forgiveness, istighfar, morning, evening, dhikr', keywords: 'sayyid istighfar, master forgiveness, morning, evening', ...H,
  },
  {
    slug: 'hadith-muslim-2708', title: 'Refuge in the perfect words of Allah',
    collection: MU, book: 'Book of Remembrance of Allah (Dhikr)', hadithNumber: 2708, narrator: 'Abu Huraira',
    arabicText: '«مَنْ قَالَ حِينَ يُمْسِي: أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ، لَمْ تَضُرَّهُ حُمَةٌ تِلْكَ اللَّيْلَةَ»',
    englishText: 'Whoever says in the evening — three times — "I seek refuge in the perfect words of Allah from the evil of what He created" — no harm will touch him that night.',
    explanation: 'The evening protection formula. (Some narrations specify the evening; a related report applies it upon leaving home as well.) Three repetitions, said with trust.',
    topics: 'dhikr, protection, evening, fear', keywords: 'refuge, perfect words, evening, harm, night', targetCount: 3, ...H,
  },
  {
    slug: 'hadith-muslim-2723', title: 'We have entered the morning and the dominion belongs to Allah',
    collection: MU, book: 'Book of Remembrance of Allah (Dhikr)', hadithNumber: 2723,
    arabicText: '«أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ…»',
    englishText: 'We have entered the morning, and with the morning all dominion belongs to Allah; all praise belongs to Allah. There is no god but Allah alone, with no partner. His is the kingdom and the praise, and He is able to do all things. My Lord, I ask You for the good of this day: its opening, its victory, its light, its blessing, and its guidance; and I seek refuge in You from the evil of what is in it and the evil of what follows it.',
    explanation: 'The morning-opening dhikr (the evening version substitutes "evening"). It frames the whole day as belonging to Allah before anything else claims ownership of the heart.',
    topics: 'dhikr, morning, evening, remembrance', keywords: 'morning, dominion, kingdom, day, evening', ...H,
  },

  // ————— Sleep & daily life —————
  {
    slug: 'hadith-bukhari-2311', title: 'Recite Ayat al-Kursi before sleeping',
    collection: BK, book: 'Book of the Virtues of the Qur\'an', hadithNumber: 2311, narrator: 'Abu Huraira',
    arabicText: '«إِذَا أَوَيْتَ إِلَى فِرَاشِكَ فَاقْرَأْ آيَةَ الْكُرْسِيِّ، إِنَّهُ لَنْ يَزَالَ عَلَيْكَ مِنَ اللَّهِ حَافِظٌ، وَلاَ يَقْرَبُكَ شَيْطَانٌ حَتَّى تُصْبِحَ»',
    englishText: 'When you go to your bed, recite Ayat al-Kursi (2:255): a guardian from Allah will remain over you, and no shaytan will come near you until morning.',
    explanation: 'The bedtime protection of the greatest verse. In the original story, Abu Huraira was guarding the zakat of Ramadan when a shaytan taught him this — and the Prophet ﷺ confirmed he had spoken truth while being a liar.',
    topics: 'sleep, protection, quran, dhikr, night', keywords: 'ayat al-kursi, bed, night, shaytan, guard', ...H,
  },
  {
    slug: 'hadith-bukhari-5017', title: 'The Prophet\'s bedtime recitation of the three surahs',
    collection: BK, book: 'Book of the Virtues of the Qur\'an', hadithNumber: 5017, narrator: 'Aisha',
    arabicText: '«كَانَ رَسُولُ اللَّهِ ﷺ إِذَا أَوَى إِلَى فِرَاشِهِ كُلَّ لَيْلَةٍ جَمَعَ كَفَّيْهِ ثُمَّ نَفَثَ فِيهِمَا، فَقَرَأَ فِيهِمَا: قُلْ هُوَ اللَّهُ أَحَدٌ، وَقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ، وَقُلْ أَعُوذُ بِرَبِّ النَّاسِ، ثُمَّ مَسَحَ بِهِمَا مَا اسْتَطَاعَ مِنْ جَسَدِهِ…»',
    englishText: 'When the Messenger of Allah ﷺ went to bed each night, he would join his cupped palms, blow into them, and recite into them: "Say: He is Allah, the One" (112), "Say: I seek refuge with the Lord of daybreak" (113), and "Say: I seek refuge with the Lord of mankind" (114) — then wipe with his hands over as much of his body as he could, beginning with his head, face, and front. He did this three times.',
    explanation: 'The Prophetic bedtime routine: three short surahs, cupped hands, breath, and a self-blessing wipe — three times. Also used for healing the sick.',
    topics: 'sleep, protection, quran, dhikr, night, healing', keywords: 'three quls, sleep, blow, palms, wipe', ...H,
  },
  {
    slug: 'hadith-bukhari-6324', title: 'In Your name, O Allah, I die and I live',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6324,
    arabicText: '«بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا»',
    englishText: 'The Prophet ﷺ said: "When you go to your bed, say: Bismika Allahumma amutu wa ahya — In Your name, O Allah, I die and I live." Then when you wake, say: "Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur — All praise belongs to Allah who gave us life after causing us to die, and to Him is the resurrection."',
    explanation: 'Sleep as a "minor death" and waking as a daily resurrection — the believer entrusts the soul to Allah by name at both edges of the night. (The full bedtime ritual is in the next record.)',
    topics: 'sleep, dua, waking, night, dhikr', keywords: 'die, live, sleep, wake, bismika', ...H,
  },
  {
    slug: 'hadith-bukhari-247', title: 'The complete bedtime dua',
    collection: BK, hadithNumber: 247, narrator: 'al-Bara\' ibn Azib',
    arabicText: '«اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لاَ مَلْجَأَ وَلاَ مَنْجَا مِنْكَ إِلاَّ إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ. فَإِنْ مُتَّ مُتَّ عَلَى الْفِطْرَةِ، فَاجْعَلْهُنَّ آخِرَ مَا تَقُولُ»',
    englishText: 'The Prophet ﷺ said: "When you go to bed, perform wudu as for prayer, lie on your right side, and say: \'O Allah, I submit myself to You, turn my face to You, entrust my affairs to You, and lean my back on You — in hope and fear of You. There is no refuge and no escape from You except to You. I believe in Your Book which You sent down and in Your Prophet whom You sent.\' If you die that night, you die upon the fitrah — so make these the last words you say."',
    explanation: 'The full Prophetic bedtime protocol: wudu, right side, and total surrender spoken aloud. Ending the day on the fitrah — the natural covenant with Allah.',
    topics: 'sleep, dua, night, fitrah, dhikr', keywords: 'bedtime, submitted, face, entrusted, fitrah', ...H,
  },
  {
    slug: 'hadith-bukhari-fatima-tasbih', title: 'Glorify Allah before sleeping — 33, 33, 34',
    collection: BK, hadithNumber: null,
    referenceNote: 'Reported in Sahih al-Bukhari; commonly numbered 5361-5362 depending on the edition, so BASIRA shows no single number.',
    narrator: 'Ali ibn Abi Talib',
    arabicText: '«أَنَّ فَاطِمَةَ عَلَيْهَا السَّلاَمُ أَتَتِ النَّبِيَّ ﷺ تَسْأَلُهُ خَادِمًا… فَقَالَ: «سَبِّحِي ثَلاَثًا وَثَلاَثِينَ، وَاحْمَدِي ثَلاَثًا وَثَلاَثِينَ، وَكَبِّرِي أَرْبَعًا وَثَلاَثِينَ، حِينَ تَأْخُذِينَ مَضْجَعَكِ»',
    englishText: 'Fatima, may Allah be pleased with her, came to the Prophet ﷺ asking for a servant to help with the grinding stone that had marked her hands. He taught her: "When you take your bed, say SubhanAllah thirty-three times, Alhamdulillah thirty-three times, and Allahu Akbar thirty-four times." Ali said: "I never left it after that — it was better than a servant."',
    explanation: 'The " Fatimah tasbih " — spiritual help instead of material help. 33+33+34 = 100 dhikras that ease the body\'s fatigue and guard the night. Ali reports he never abandoned it.',
    topics: 'sleep, dhikr, night, tasbih', keywords: 'fatima, 33, 34, servant, sleep, tasbih', targetCount: 33, ...P,
  },
  {
    slug: 'hadith-bukhari-6312', title: 'The waking dua of the Prophet',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6312, narrator: 'Hudhayfa ibn al-Yaman',
    arabicText: '«كُنَّا إِذَا نَامَ رَسُولُ اللَّهِ ﷺ… فَيَقُولُ: الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ»',
    englishText: 'When the Prophet ﷺ woke at night, he would say: "Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur — All praise belongs to Allah, who gave us life after He caused us to die, and to Him is the resurrection."',
    explanation: 'The first words of the Muslim morning — and of every mid-night waking: gratitude for life restored, and the reminder that the final rising is to Allah.',
    topics: 'waking, dua, morning, night, dhikr', keywords: 'wake up, praise, resurrection, life', ...H,
  },
  {
    slug: 'hadith-bukhari-5376', title: 'Mention Allah\'s name and eat with your right hand',
    collection: BK, book: 'Book of Food (Kitab al-At\'imah)', hadithNumber: 5376, narrator: 'Umar ibn Abi Salama',
    arabicText: '«يَا غُلاَمُ، سَمِّ اللَّهَ، وَكُلْ بِيَمِينِكَ، وَكُلْ مِمَّا يَلِيكَ»',
    englishText: 'The Prophet ﷺ said to his young stepson: "O boy, mention the name of Allah, eat with your right hand, and eat from what is in front of you."',
    explanation: 'The complete Islamic table etiquette for children in one sentence — taught gently to a boy at the Prophet\'s ﷺ own table.',
    topics: 'eating, food, manners, children', keywords: 'bismillah, right hand, food, eat, manners', ...H,
  },
  {
    slug: 'hadith-abudawud-1856', title: 'If you forget to say Bismillah',
    collection: AD, book: 'Book of Food', hadithNumber: 1856, narrator: 'Aisha', grade: 'Sahih (authenticated)',
    arabicText: '«إِذَا أَكَلَ أَحَدُكُمْ فَلْيَذْكُرِ اسْمَ اللَّهِ، فَإِنْ نَسِيَ أَنْ يَذْكُرَ اسْمَ اللَّهِ فِي أَوَّلِهِ فَلْيَقُلْ: بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ»',
    englishText: 'When one of you eats, let him mention the name of Allah. If he forgets to mention Allah\'s name at the beginning, let him say: "Bismillahi awwalahu wa akhirahu — In the name of Allah at its beginning and its end."',
    explanation: 'Also recorded by at-Tirmidhi. Islam builds recovery into practice: forgetting does not waste the meal — one phrase restores the blessing.',
    topics: 'eating, food, dua, forgetfulness', keywords: 'bismillah, forgot, beginning, end, food', ...H,
  },
  {
    slug: 'hadith-tirmidhi-3458', title: 'Praise after eating',
    collection: TM, book: 'Book of Supplications', hadithNumber: 3458, narrator: 'Mu\'adh ibn Anas', grade: 'Hasan Sahih (sound)',
    arabicText: '«مَنْ أَكَلَ طَعَامًا فَقَالَ: الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلاَ قُوَّةٍ، غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ»',
    englishText: 'Whoever eats food and says: "Alhamdu lillahil-ladhi at\'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah — All praise belongs to Allah who fed me this and provided it for me without any effort or power on my part" — his previous sins are forgiven.',
    explanation: 'Gratitude for a single meal, articulated precisely, weighs against a lifetime of sin. The dua recognizes that even "our own" earning is provision.',
    topics: 'eating, food, dua, gratitude, forgiveness', keywords: 'after eating, praise, provided, food', ...H,
  },
  {
    slug: 'hadith-muslim-2734', title: 'Praise to Allah who made us Muslims',
    collection: MU, book: 'Book of Remembrance of Allah (Dhikr)', hadithNumber: 2734,
    arabicText: '«الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ»',
    englishText: 'Praise be to Allah who fed us and gave us drink and made us Muslims.',
    explanation: 'The shorter after-meal dua — gratitude combining sustenance and the greatest gift of all: guidance.',
    topics: 'eating, food, dua, gratitude', keywords: 'fed, drink, muslim, after meal', ...H,
  },
  {
    slug: 'hadith-muslim-2018', title: 'Mention Allah when entering your home',
    collection: MU, book: 'Book of Drinks (Kitab al-Ashriba)', hadithNumber: 2018, narrator: 'Jabir ibn Abdullah',
    arabicText: '«إِذَا دَخَلَ الرَّجُلُ بَيْتَهُ فَذَكَرَ اللَّهَ عِنْدَ دُخُولِهِ وَعِنْدَ طَعَامِهِ قَالَ الشَّيْطَانُ: لاَ مَبِيتَ لَكُمْ وَلاَ عَشَاءَ»',
    englishText: 'If a man enters his house mentioning Allah\'s name upon entering and upon his food, Satan says: "You have no lodging tonight and no supper." But if he enters without mentioning Allah, Satan says: "You have found lodging for the night" — and if he does not mention Allah over the food, Satan says: "You have found lodging and supper."',
    explanation: 'The unseen economics of the home: bismillah and salam at the door and at the table lock shaytan out of the household\'s evening. Pair it with the Qur\'anic command to greet your family (24:61).',
    topics: 'entering home, dua, protection, family, eating', keywords: 'house, home, enter, shaytan, lodging, supper', ...H,
  },
  {
    slug: 'hadith-abudawud-5095', title: 'When leaving the home',
    collection: AD, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: 5095, narrator: 'Anas ibn Malik', grade: 'Hasan Sahih (sound)',
    arabicText: '«بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ. يُقَالُ لَهُ: هُدِيتَ وَكُفِيتَ وَوُقِيتَ، وَتَنَحَّى عَنْهُ الشَّيْطَانُ»',
    englishText: 'Whoever says upon leaving his house: "Bismillah, tawakkaltu \'alallah, wa la hawla wa la quwwata illa billah — In the name of Allah; I place my trust in Allah; there is no power and no might except by Allah" — it is said to him: "You are guided, you are sufficed, you are protected," and Satan steps away from him.',
    explanation: 'The departure passport of the believer: threefold divine cover (guidance, sufficiency, protection) declared over the day\'s journey.',
    topics: 'leaving home, dua, protection, trust', keywords: 'leave, house, trust, guidance, protected', ...H,
  },
  {
    slug: 'hadith-abudawud-5096', title: 'The reported dua for entering the home',
    collection: AD, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: null,
    referenceNote: 'Commonly cited as Abu Dawud no. 5096, but several scholars graded this particular narration weak; BASIRA therefore shows no number and marks it pending.',
    verificationStatus: 'REFERENCE_PENDING', reviewer: 'BASIRA Editorial Review', lastReviewedAt: '2025-01-15', sourceType: 'HADITH',
    arabicText: '«بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى رَبِّنَا تَوَكَّلْنَا. ثُمَّ لِيُسَلِّمْ عَلَى أَهْلِهِ»',
    englishText: 'In the name of Allah we enter, and in the name of Allah we leave, and upon our Lord we place our trust — then let him greet his family with salam.',
    explanation: 'BASIRA flags this dua transparently: its chain is discussed (graded weak by several scholars). What is firmly established is the meaning around it — mentioning Allah\'s name when entering (Sahih Muslim 2018, in this collection above) and greeting the family with salam (Qur\'an 24:61). You may say this dua while knowing its grading is debated.',
    topics: 'entering home, dua, protection', keywords: 'enter, home, house, salam, family', ...P,
  },
  {
    slug: 'hadith-muslim-1342', title: 'The traveler\'s takbir and dua',
    collection: MU, book: 'Book of Hajj', hadithNumber: 1342, narrator: 'Abdullah ibn Umar',
    arabicText: '«سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ»',
    englishText: 'When the Prophet ﷺ mounted his camel for travel he would say Allahu Akbar three times, then: "Subhana alladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun — Glory to Him who subjected this to us, and we could never have accomplished it ourselves; indeed to our Lord we are returning." Then he would supplicate: "O Allah, we ask You on this journey of ours for righteousness and mindfulness of You, and for deeds that please You… protect us and those with us, and make what is before us easy for us."',
    explanation: 'The full travel sunnah. The opening line mirrors Qur\'an 43:13-14 — the vehicle, plane, or car is "subjected" to us by Allah alone. The hadith continues: "There is no power and no might except by Allah" and then the traveler adds extra dhikr and raises his voice.',
    topics: 'travel, dua, journey, dhikr', keywords: 'travel, trip, car, flight, journey, camel', ...H,
  },
  {
    slug: 'hadith-bukhari-6346', title: 'The dua of distress',
    collection: BK, book: 'Book of Invocations (Kitab ad-Da\'awat)', hadithNumber: 6346, narrator: 'Abdullah ibn Abbas',
    arabicText: '«لاَ إِلَهَ إِلاَّ اللَّهُ الْعَظِيمُ الْحَلِيمُ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ»',
    englishText: 'The Messenger of Allah ﷺ would say at times of distress: "There is no god but Allah, the Great, the Forbearing; there is no god but Allah, Lord of the Magnificent Throne; there is no god but Allah, Lord of the heavens and the earth, and Lord of the Noble Throne."',
    explanation: 'The distress formula built entirely from tawhid — because the heart in crisis needs to remember Who actually runs the heavens, the earth, and the throne above them all.',
    topics: 'dua, difficulty, distress, fear, anxiety', keywords: 'distress, anxiety, panic, throne, no god but allah', ...H,
  },
  {
    slug: 'hadith-bukhari-1166', title: 'Salat al-Istikhara — the consultation prayer',
    collection: BK, book: 'Book of Istikhara', hadithNumber: 1166, narrator: 'Jabir ibn Abdullah',
    arabicText: '«إِذَا هَمَّ أَحَدُكُمْ بِالأَمْرِ فَلْيَرْكَعْ رَكْعَتَيْنِ مِنْ غَيْرِ الْفَرِيضَةِ، ثُمَّ لِيَقُلْ: اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلاَ أَقْدِرُ، وَتَعْلَمُ وَلاَ أَعْلَمُ، وَأَنْتَ عَلاَّمُ الْغُيُوبِ. اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي ثُمَّ بَارِكْ لِي فِيهِ، وَإِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الأَمْرَ شَرٌّ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاصْرِفْهُ عَنِّي وَاصْرِفْنِي عَنْهُ، وَاقْدُرْ لِيَ الْخَيْرَ حَيْثُ كَانَ، ثُمَّ رَضِّنِي بِهِ»',
    englishText: 'When one of you intends a matter, let him pray two rakʿahs outside the obligatory prayers, then say: "O Allah, I seek Your guidance by Your knowledge and Your power, and I ask You of Your immense bounty — for You are able and I am not; You know and I do not; You are the Knower of all that is hidden. O Allah, if You know that this matter is good for my religion, my livelihood, and the outcome of my affair, then decree it for me, make it easy for me, and bless it for me. And if You know it is bad for my religion, my livelihood, and the outcome of my affair, then turn it away from me and turn me away from it, and decree for me the good wherever it is, and then make me content with it."',
    explanation: 'The decision-making prayer: two rakʿahs + this dua, naming the specific matter ("this matter" — you mention it, e.g. "this job offer"). Istikhara asks Allah to choose for you — the outcome is felt as ease or discomfort, or events simply unfold. It pairs with consultation (shura) and effort, not instead of them.',
    topics: 'dua, decision, guidance, istikhara, difficulty', keywords: 'istikhara, decision, choice, marriage, job, guidance', ...H,
  },
  {
    slug: 'hadith-muslim-2202', title: 'The dua for the sick',
    collection: MU, book: 'Book of Greetings (Salam)', hadithNumber: 2202, narrator: 'Anas ibn Malik',
    arabicText: '«اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَاسَ، اشْفِ وَأَنْتَ الشَّافِي، لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ، شِفَاءً لاَ يُغَادِرُ سَقَمًا»',
    englishText: 'The Prophet ﷺ would visit the sick and supplicate: "O Allah, Lord of mankind, remove the harm. Heal — for You are the Healer; there is no healing like Your healing — a healing that leaves no trace of illness."',
    explanation: 'The complete prophetic visiting-the-sick dua. It affirms that Allah is ash-Shafi (The Healer) while medicine is a means, and pairs with modern treatment — the Prophet ﷺ himself commanded taking medicine.',
    topics: 'illness, sickness, dua, healing, visiting sick', keywords: 'sick, patient, cure, heal, disease', ...H,
  },
  {
    slug: 'hadith-tirmidhi-2083', title: 'Seven times for the one you visit',
    collection: TM, book: 'Book of Visiting the Sick', hadithNumber: 2083, narrator: 'Abdullah ibn Abbas', grade: 'Hasan (sound)',
    arabicText: '«مَنْ عَادَ مَرِيضًا لَمْ يَحْضُرْ أَجَلُهُ فَقَالَ عِنْدَهُ سَبْعَ مَرَّاتٍ: أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ، إِلاَّ عَافَاهُ اللَّهُ مِنْ ذَلِكَ الْمَرَضِ»',
    englishText: 'Whoever visits a sick person whose appointed time has not yet come and says beside him seven times: "As\'alullahal-\'Adhim Rabbal-\'Arshil-\'Adhim an yashfiyak — I ask Allah the Great, Lord of the Magnificent Throne, to cure you" — Allah will cure him of that disease.',
    explanation: 'The sevenfold visitor\'s dua. The condition "whose appointed time has not come" humbles the outcome to Allah\'s decree — we ask with full hope, He heals as He wills.',
    topics: 'illness, sickness, dua, visiting sick', keywords: 'seven times, visit, patient, throne, cure', targetCount: 7, ...H,
  },
  {
    slug: 'hadith-bukhari-1032', title: 'The dua for rain',
    collection: BK, book: 'Book of Rain Prayers (Kitab al-Istisqa)', hadithNumber: 1032, narrator: 'Anas ibn Malik',
    arabicText: '«اللَّهُمَّ صَيِّبًا نَافِعًا»',
    englishText: 'The Prophet ﷺ was on the pulpit when rain began to fall, and he raised his hands and supplicated: "Allahumma sayyiban naafiʿan — O Allah, make it a beneficial, abundant rain."',
    explanation: 'Both the dua for rain when praying for it, and for blessing the rain when it arrives. Related narrations teach asking for its good, refuge from its harm, and saying "We have been given rain by Allah\'s bounty" (Mutirna bi-fadlillah) after it.',
    topics: 'rain, dua, weather', keywords: 'rain, beneficial, weather, istisqa, storm', ...H,
  },
  {
    slug: 'hadith-muslim-713', title: 'Entering and leaving the mosque',
    collection: MU, book: 'Book of Prayer', hadithNumber: 713,
    arabicText: '«إِذَا دَخَلَ أَحَدُكُمُ الْمَسْجِدَ فَلْيَبْدَأْ بِالصَّلاَةِ عَلَى النَّبِيِّ ﷺ وَلْيَقُلْ: اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ، وَإِذَا خَرَجَ فَلْيَقُلْ: اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ»',
    englishText: 'When one of you enters the mosque, let him begin by sending blessings upon the Prophet ﷺ and say: "Allahumma iftah li abwaba rahmatik — O Allah, open for me the doors of Your mercy." And when he leaves, let him say: "Allahumma inni as\'aluka min fadlik — O Allah, I ask You of Your bounty."',
    explanation: 'The paired mosque thresholds: entering through doors of mercy, exiting through the gate of provision — the masjid framed as the believer\'s exchange counter between the two.',
    topics: 'masjid, mosque, dua', keywords: 'enter, mosque, mercy, leave, bounty', ...H,
  },

  // ————— Family & society —————
  {
    slug: 'hadith-bukhari-5971', title: 'Your mother, three times, then your father',
    collection: BK, book: 'Book of Manners (Kitab al-Adab)', hadithNumber: 5971, narrator: 'Abu Huraira',
    arabicText: '«جَاءَ رَجُلٌ إِلَى رَسُولِ اللَّهِ ﷺ فَقَالَ: يَا رَسُولَ اللَّهِ، مَنْ أَحَقُّ النَّاسِ بِحُسْنِ صَحَابَتِي؟ قَالَ: أُمُّكَ. قَالَ: ثُمَّ مَنْ؟ قَالَ: أُمُّكَ. قَالَ: ثُمَّ مَنْ؟ قَالَ: أُمُّكَ. قَالَ: ثُمَّ مَنْ؟ قَالَ: أَبُوكَ»',
    englishText: 'A man came to the Messenger of Allah ﷺ and asked: "O Messenger of Allah, who among people most deserves my good company?" He said: "Your mother." The man asked: "Then who?" He said: "Your mother." He asked again: "Then who?" He said: "Your mother." He asked: "Then who?" He said: "Your father."',
    explanation: 'The famous 3:1 weighting of the mother in companionship — reflecting pregnancy, birth, and nursing. The father follows immediately: both are honored, in precise proportion.',
    topics: 'parents, mother, father, kindness, manners', keywords: 'mother, mom, father, dad, company, rights', ...H,
  },
  {
    slug: 'hadith-muslim-2551', title: 'Let him be humiliated — the one who misses serving his parents',
    collection: MU, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 2551, narrator: 'Abu Huraira',
    arabicText: '«رَغِمَ أَنْفُهُ، ثُمَّ رَغِمَ أَنْفُهُ، ثُمَّ رَغِمَ أَنْفُهُ. قِيلَ: مَنْ يَا رَسُولَ اللَّهِ؟ قَالَ: مَنْ أَدْرَكَ أَبَوَيْهِ عِنْدَ الْكِبَرِ، أَحَدَهُمَا أَوْ كِلَيْهِمَا، فَلَمْ يَدْخُلِ الْجَنَّةَ»',
    englishText: 'The Prophet ﷺ said: "Let him be humiliated — let him be humiliated — let him be humiliated." It was asked: "Who, O Messenger of Allah?" He said: "The one who finds one or both of his parents in old age but does not enter Paradise (by serving them)."',
    explanation: 'Old-age parents are an open gate to Paradise placed directly in one\'s home. The triple "raghima anfuh" is the strongest possible Arabic emphasis — said out of mercy, to wake us before it is too late.',
    topics: 'parents, kindness, jannah, manners', keywords: 'humiliated, parents, old age, paradise, serve', ...H,
  },
  {
    slug: 'hadith-tirmidhi-1899', title: 'Allah\'s pleasure is in the parent\'s pleasure',
    collection: TM, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 1899, grade: 'Hasan (sound)',
    arabicText: '«رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ، وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ»',
    englishText: 'The pleasure of the Lord lies in the pleasure of the parent, and the displeasure of the Lord lies in the displeasure of the parent.',
    explanation: 'Vertical alignment: how you stand with your parents is how you stand with Allah. (Understood within obedience to Allah — a parent\'s pleasure never overrides Allah\'s commands.)',
    topics: 'parents, kindness, manners, pleasure', keywords: 'pleasure, displeasure, parent, lord', ...H,
  },
  {
    slug: 'hadith-nasai-3104', title: 'Paradise is beneath her feet',
    collection: NS, book: 'Book of Jihad', hadithNumber: 3104, grade: 'Hasan (graded sahih by some scholars)',
    arabicText: '«الْزَمْهَا فَإِنَّ الْجَنَّةَ تَحْتَ رِجْلَيْهَا»',
    englishText: 'A man asked the Prophet ﷺ about the rights of his mother (after she passed). He said: "Stay close to her — for Paradise is beneath her feet."',
    explanation: 'Staying devoted to the mother — in her life and after her death (through dua, charity, and honoring her ties). A famous image of the rank of mothers; BASIRA notes the report is graded hasan and considered sahih by some scholars.',
    topics: 'parents, mother, jannah, kindness', keywords: 'paradise, feet, mother, stay', ...H,
  },
  {
    slug: 'hadith-bukhari-5065', title: 'O young people, whoever can marry, let him marry',
    collection: BK, book: 'Book of Marriage (Kitab an-Nikah)', hadithNumber: 5065,
    arabicText: '«يَا مَعْشَرَ الشَّبَابِ، مَنِ اسْتَطَاعَ مِنْكُمُ الْبَاءَةَ فَلْيَتَزَوَّجْ، فَإِنَّهُ أَغَضُّ لِلْبَصَرِ وَأَحْصَنُ لِلْفَرْجِ، وَمَنْ لَمْ يَسْتَطِعْ فَعَلَيْهِ بِالصَّوْمِ فَإِنَّهُ لَهُ وِجَاءٌ»',
    englishText: 'O young people, whoever among you is able to marry, let him marry — for it is more restraining for the gaze and safer for the private parts. And whoever is not able, let him fast, for it is a shield for him.',
    explanation: 'Islam\'s realistic approach to desire: marriage when able, fasting as spiritual armor when not. Marriage is framed as protection and dignity, not mere license.',
    topics: 'marriage, youth, fasting, chastity', keywords: 'marry, young, marriage, fast, gaze', ...H,
  },
  {
    slug: 'hadith-tirmidhi-3895', title: 'The best of you are the best to their families',
    collection: TM, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 3895, grade: 'Hasan Sahih (sound)',
    arabicText: '«خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ، وَأَنَا خَيْرُكُمْ لِأَهْلِي»',
    englishText: 'The best of you are those who are best to their families — and I am the best of you to my family.',
    explanation: 'The home is the true exam hall of character: public piety is easy; private gentleness is the proof. The Prophet ﷺ testified about his own household first.',
    topics: 'marriage, family, manners, kindness, wife', keywords: 'best, family, wife, household, character', ...H,
  },
  {
    slug: 'hadith-bukhari-2076', title: 'May Allah have mercy on the easy-going man',
    collection: BK, book: 'Book of Sales (Kitab al-Buyu)', hadithNumber: 2076, narrator: 'Jabir ibn Abdullah',
    arabicText: '«رَحِمَ اللَّهُ رَجُلاً سَمْحًا إِذَا بَاعَ، وَإِذَا اشْتَرَى، وَإِذَا اقْتَضَى»',
    englishText: 'May Allah have mercy on a man who is easy-going when he sells, when he buys, and when he asks for his due.',
    explanation: 'The divine mercy-invocation for commercial softness: no aggressive haggling, no harshness in collecting debts — ease at every transactional moment.',
    topics: 'business, trade, kindness, manners', keywords: 'easy, sell, buy, debt, collect', ...H,
  },
  {
    slug: 'hadith-bukhari-2079', title: 'The two parties of a transaction have the choice',
    collection: BK, book: 'Book of Sales (Kitab al-Buyu)', hadithNumber: 2079, narrator: 'Hakim ibn Hizam',
    arabicText: '«إِنَّ الْبَيِّعَيْنِ بِالْخِيَارِ مَا لَمْ يَتَفَرَّقَا، فَإِنْ صَدَقَا وَبَيَّنَا بُورِكَ لَهُمَا فِي بَيْعِهِمَا، وَإِنْ كَتَمَا وَكَذَبَا مُحِقَتْ بَرَكَةُ بَيْعِهِمَا»',
    englishText: 'The buyer and seller have the option (to cancel) as long as they have not separated. If they were truthful and clear, their transaction is blessed; if they concealed and lied, the blessing of their transaction is erased.',
    explanation: 'The "cooling-off" principle of Islamic commerce, 1400 years early — plus the condition that makes trade blessed: transparency. Hiding defects voids the barakah even when the sale stands.',
    topics: 'business, trade, honesty', keywords: 'buyer, seller, option, truth, defect, cancel', ...H,
  },
  {
    slug: 'hadith-muslim-102', title: 'Whoever cheats us is not one of us',
    collection: MU, book: 'Book of Transactions (Kitab al-Buyu)', hadithNumber: 102, narrator: 'Abu Huraira',
    arabicText: '«مَنْ غَشَّنَا فَلَيْسَ مِنَّا»',
    englishText: 'The Prophet ﷺ passed by a pile of grain, put his hand into it and felt wetness inside. He asked: "What is this, O owner of the grain?" He said: "Rain caught it, O Messenger of Allah." He said: "Why did you not place the wet grain on top so people could see it? Whoever deceives us is not one of us."',
    explanation: 'Concealing a defect is deception (ghish) — the Prophet ﷺ distances it from Islam entirely. Honest sellers display flaws; buyers get what they see.',
    topics: 'business, trade, lying, honesty, cheating', keywords: 'cheat, deceive, wet, grain, hidden defect', ...H,
  },
  {
    slug: 'hadith-tirmidhi-1209', title: 'The truthful, trustworthy merchant',
    collection: TM, book: 'Book of Transactions (Kitab al-Buyu)', hadithNumber: 1209, grade: 'Hasan (sound)',
    arabicText: '«التَّاجِرُ الصَّدُوقُ الأَمِينُ مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاءِ»',
    englishText: 'The truthful, trustworthy merchant will be with the prophets, the utterly truthful, and the martyrs.',
    explanation: 'Honest business is not just "permitted" — its practitioners are seated with the highest ranks of humanity on the Day of Resurrection. Commerce as worship.',
    topics: 'business, trade, honesty', keywords: 'merchant, truthful, trustworthy, prophets, martyrs', ...H,
  },

  // ————— Hereafter —————
  {
    slug: 'hadith-bukhari-7498', title: 'What no eye has seen',
    collection: BK, hadithNumber: 7498, narrator: 'Abu Huraira',
    arabicText: '«أَعَدَدْتُ لِعِبَادِي الصَّالِحِينَ مَا لاَ عَيْنٌ رَأَتْ، وَلاَ أُذُنٌ سَمِعَتْ، وَلاَ خَطَرَ عَلَى قَلْبِ بَشَرٍ»',
    englishText: 'Allah, the Exalted, said (hadith qudsi): "I have prepared for My righteous servants what no eye has seen, no ear has heard, and no human heart has ever imagined."',
    explanation: 'A hadith qudsi (divine wording beyond the Qur\'an) about Jannah: its delights are literally beyond human imagination — our best guesses are underestimations. Echoed in Qur\'an 32:17.',
    topics: 'jannah, paradise, reward, hereafter', keywords: 'eye, ear, heart, prepared, reward, unseen', ...H,
  },
  {
    slug: 'hadith-bukhari-isra-miraj', title: 'The Night Journey and Ascension',
    collection: BK, hadithNumber: null,
    referenceNote: 'The long Miʿraj hadith appears in Sahih al-Bukhari in several places (commonly cited as nos. 3207, 3887 and 7443), so BASIRA shows no single number.',
    narrator: 'Anas ibn Malik',
    englishText: 'The Prophet ﷺ was carried on al-Buraq (a white riding beast) with Jibril. He passed by Madyan, the tree of Musa at Tuwa, and Mount Sinai, then led the prophets in prayer at Bayt al-Maqdis (Jerusalem). Then he was raised through the heavens: in the first heaven he met Adam; in the second, Isa and Yahya; in the third, Yusuf; in the fourth, Idris; in the fifth, Harun; in the sixth, Musa; and in the seventh, Ibrahim leaning against the Bayt al-Ma\'mur. Then came the lote tree of the utmost boundary (sidrat al-muntaha) and the fifty prayers — reduced through Musa\'s counsel to five prayers enjoined, equal in reward to fifty. "The decree is irrevocable."',
    explanation: 'The Isra (night journey to Jerusalem) is Qur\'anic (17:1); the Miʿraj (ascension through the heavens) is detailed in Bukhari and Muslim. From it Muslims received the gift of the five daily prayers. BASIRA notes the number varies by narration location.',
    topics: 'seerah, isra miraj, prayer, prophet, night journey', keywords: 'buraq, jerusalem, heavens, ascension, mi\'raj, isra', ...P,
  },

  // ————— Character & manners (famous references, added 2026-09) —————
  {
    slug: 'hadith-bukhari-10', title: 'The Muslim is the one people are safe from',
    collection: BK, book: 'Book of Belief (Kitab al-Iman)', hadithNumber: 10, narrator: 'Abdullah ibn Amr',
    arabicText: '«الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ»',
    englishText: 'The Muslim is the one from whose tongue and hand the Muslims are safe.',
    explanation: 'One of the most concise definitions of a Muslim in the Sunnah: not merely a label or a birthright, but a person others are safe from — no harm in speech, no harm in action. Early scholars read "the Muslims" broadly as "the people" in some narrations of Muslim, extending the circle of safety.',
    topics: 'manners, speech, harm, kindness, faith, character', keywords: 'muslim, tongue, hand, safe, harm, definition', ...H,
  },
  {
    slug: 'hadith-muslim-223', title: 'Purity is half of faith',
    collection: MU, book: 'Book of Mosques (Kitab al-Masajid)', hadithNumber: 223, narrator: 'Abu Malik al-Ash\'ari',
    arabicText: '«الطُّهُورُ شَطْرُ الإِيمَانِ»',
    englishText: 'Purity is half of faith.',
    explanation: 'The opening words of a longer hadith in which the Prophet ﷺ also said "Alhamdulillah fills the scale". Scholars explain that purification (taharah) is the gateway of worship: no prayer is valid without it, so it is described as half of faith\'s practice. Physical cleanliness mirrors the inner purity of intention.',
    topics: 'purity, wudu, faith, cleanliness', keywords: 'purity, taharah, clean, half, iman', ...H,
  },
  {
    slug: 'hadith-muslim-2664', title: 'The strong believer',
    collection: MU, book: 'Book of Divine Decree (Kitab al-Qadar)', hadithNumber: 2664, narrator: 'Abu Huraira',
    arabicText: '«الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ، وَفِي كُلٍّ خَيْرٌ»',
    englishText: 'The strong believer is better and more beloved to Allah than the weak believer — while there is good in both.',
    explanation: 'Strength here is read as strength of faith and character as well as physical ability. The closing words matter: "in both is good" — the hadith honors effort and never mocks weakness. The Prophet ﷺ then taught: "Be eager for what benefits you, seek help from Allah, and do not be helpless."',
    topics: 'strength, faith, effort, determination, anxiety', keywords: 'strong, weak, believer, resolve, help', ...H,
  },
  {
    slug: 'hadith-muslim-2594', title: 'Gentleness beautifies everything',
    collection: MU, book: 'Book of Good Manners (Kitab al-Birr)', hadithNumber: 2594, narrator: 'Aisha',
    arabicText: '«إِنَّ الرِّفْقَ لاَ يَكُونُ فِي شَيْءٍ إِلاَّ زَانَهُ، وَلاَ يُنْزَعُ مِنْ شَيْءٍ إِلاَّ شَانَهُ»',
    englishText: 'Gentleness is not present in anything without beautifying it, and it is not removed from anything without disfiguring it.',
    explanation: 'Aisha reported that the Prophet ﷺ said this about an incident where two men were harsh with a Bedouin. Rifq (gentleness, kindness in approach) is a mark of prophetic character: it adorns matters of worship, family, teaching, and leadership — and its absence ruins them.',
    topics: 'gentleness, kindness, manners, character, mercy', keywords: 'gentle, rifaq, kindness, harsh, soft', ...H,
  },
  {
    slug: 'hadith-tirmidhi-1162', title: 'The most complete believers have the best character',
    collection: TM, book: 'Book of Righteousness (Kitab al-Birr)', hadithNumber: 1162, grade: 'Hasan Sahih (sound)',
    narrator: 'Abu Huraira',
    arabicText: '«أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا»',
    englishText: 'The most complete of the believers in faith are those with the best character.',
    explanation: 'Faith (iman) is measured here by character (khuluq) — how one treats family, neighbors, strangers, and even animals. A parallel report adds: "…and the best of you are those best to their womenfolk." Character is the outward proof of inward belief.',
    topics: 'character, manners, faith, family, kindness', keywords: 'complete, believer, character, khuluq, best', ...H,
  },
];
